In [1]:
import numpy as np
import pandas as pd
import os

/home/euphrates/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/euphrates/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [5]:
for i in os.listdir():
    print({i},pd.read_csv(i).shape)

{'3.csv'} (25, 130)
{'noncon-E2(portven-matched).csv'} (8, 130)
{'0.csv'} (36, 130)
{'4.csv'} (27, 130)
{'5.csv'} (54, 130)
{'noncon-E1.csv'} (9, 130)
{'1.csv'} (3, 131)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

In [9]:
len([i for i in pd.read_csv('0.csv').columns if i in pd.read_csv('noncon-E1.csv').columns])

130

In [10]:
df1 = pd.read_csv('0.csv')

In [11]:
df2 = pd.read_csv('noncon-E1.csv')

In [43]:
pd.set_option("display.max_columns",140)

In [47]:
pd.set_option("display.max_rows",30)

In [15]:
df1.head()

,diagnostics_Versions_PyRadiomics,diagnostics_Versions_Numpy,diagnostics_Versions_SimpleITK,diagnostics_Versions_PyWavelet,diagnostics_Versions_Python,diagnostics_Configuration_Settings,diagnostics_Configuration_EnabledImageTypes,diagnostics_Image-original_Hash,diagnostics_Image-original_Dimensionality,diagnostics_Image-original_Spacing,diagnostics_Image-original_Size,diagnostics_Image-original_Mean,diagnostics_Image-original_Minimum,diagnostics_Image-original_Maximum,diagnostics_Mask-original_Hash,diagnostics_Mask-original_Spacing,diagnostics_Mask-original_Size,diagnostics_Mask-original_BoundingBox,diagnostics_Mask-original_VoxelNum,diagnostics_Mask-original_VolumeNum,diagnostics_Mask-original_CenterOfMassIndex,diagnostics_Mask-original_CenterOfMass,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,original_shape_Sphericity,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_VoxelVolume,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,original_firstorder_Minimum,original_firstorder_Range,original_firstorder_RobustMeanAbsoluteDeviation,original_firstorder_RootMeanSquared,original_firstorder_Skewness,original_firstorder_TotalEnergy,original_firstorder_Uniformity,original_firstorder_Variance,original_glcm_Autocorrelation,original_glcm_ClusterProminence,original_glcm_ClusterShade,original_glcm_ClusterTendency,original_glcm_Contrast,original_glcm_Correlation,original_glcm_DifferenceAverage,original_glcm_DifferenceEntropy,original_glcm_DifferenceVariance,original_glcm_Id,original_glcm_Idm,original_glcm_Idmn,original_glcm_Idn,original_glcm_Imc1,original_glcm_Imc2,original_glcm_InverseVariance,original_glcm_JointAverage,original_glcm_JointEnergy,original_glcm_JointEntropy,original_glcm_MCC,original_glcm_MaximumProbability,original_glcm_SumAverage,original_glcm_SumEntropy,original_glcm_SumSquares,original_gldm_DependenceEntropy,original_gldm_DependenceNonUniformity,original_gldm_DependenceNonUniformityNormalized,original_gldm_DependenceVariance,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_glrlm_GrayLevelNonUniformity,original_glrlm_GrayLevelNonUniformityNormalized,original_glrlm_GrayLevelVariance,original_glrlm_HighGrayLevelRunEmphasis,original_glrlm_LongRunEmphasis,original_glrlm_LongRunHighGrayLevelEmphasis,original_glrlm_LongRunLowGrayLevelEmphasis,original_glrlm_LowGrayLevelRunEmphasis,original_glrlm_RunEntropy,original_glrlm_RunLengthNonUniformity,original_glrlm_RunLengthNonUniformityNormalized,original_glrlm_RunPercentage,original_glrlm_RunVariance,original_glrlm_ShortRunEmphasis,original_glrlm_ShortRunHighGrayLevelEmphasis,original_glrlm_ShortRunLowGrayLevelEmphasis,original_glszm_GrayLevelNonUniformity,original_glszm_GrayLevelNonUniformityNormalized,original_glszm_GrayLevelVariance,original_glszm_HighGrayLevelZoneEmphasis,original_glszm_LargeAreaEmphasis,original_glszm_LargeAreaHighGrayLevelEmphasis,original_glszm_LargeAreaLowGrayLevelEmphasis,original_glszm_LowGrayLevelZoneEmphasis,original_glszm_SizeZoneNonUniformity,original_glszm_SizeZoneNonUniformityNormalized,original_glszm_SmallAreaEmphasis,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,case_id
0,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},c7d1da3ec777e61e94f9cdc53260a21d894445bb,3D,"(5.0, 0.94140625, 0.94140625)","(107, 512, 512)",-478.172183,-1024.0,3071.0,3873b004125fa982d67745f014f98ecc7a67279e,"(5.0, 0.94140625, 0.94140625)","(107, 512, 512)","(22, 238, 124, 37, 150, 276)",158390,39,"(np.float64(40.11286066039523), np.float64(327...","(249.49858816153957, 308.7081972553902, -200.5...",0.345872,0.154006,58.334545,378.781098,260.098073,249.650217,152.414115,281.013727,701356.774591,131.009664,0.439681,86823.803829,0.123794,701862.303925,8.0,118.0,1.025027e+09,2.784517,55.0,3.133570,227.0,33.720230,68.260604,74.0,-104.0,331.0,23.318152,80.445860,-0.575670,4.542127e+09,0.171705,1812.026441,71.398104,182.081440,-11.193175,7.461220,3.292332,0.385767,1.352817,2.117705,1.434617,0.546405,0.496766,0.986117,0.921951,-0.054889,0.462564,0.460189,8.387784,0.037662,5.281337,0.398943,0.085787,16.775568,3.447845,2.688388,6.295166,12542.177499,0.079185,12.177740,27196.410051,2.985695,71.036581,59.341916,4504.379380,0.864531,0.017880,0.089758,5.398011,0.002663,19567.209219,0.159563,3.298232,69.936935,2.101398,152.567424,0.035204,0.018680,3.827202,79172.901267,0.643705,0.774322,0.423591,0.829469,57.235802,0.016062,1560.672492,0.128039,7.555157,55.521208,154502.025597,1.196696e+07,2091.011470,0.034156,4568.521864,0.374807,0.635815,35.884131,0.023299,5.316951,0.076956,154333.168482,127.208308,0.000047,100.270650,0.028493,0.004105,case_00126
1,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},a013521888156909a4a2b40e5110df5f380dcdf4,3D,"(3.0, 0.9765625, 0.9765625)","(105, 512, 512)",-543.238566,-1024.0,1315.0,b34daa35c8b1e86fa58f8f5b0aa7810bc9d57773,"(3.0, 0.9765625, 0.9765625)","(105, 512, 512)","(35, 260, 151, 46, 94, 227)",175025,15,"(np.float64(56.17795172118269), np.float64(310...","(256.98616715469217, 303.3005106413369, -168.5...",0.416931,0.180729,55.232812,305.611088,222.745511,221.255531,132.700817,223.053562,500527.501106,127.418824,0.420479,72503.400300,0.144854,500750.541687,11.0,147.0,1.781937e+09,3.053624,74.0,2.817786,258.0,42.596078,86.289684,95.0,-119.0,377.0,30.703972,100.901146,-0.574102,5.098162e+09,0.139251,2735.131658,85.701684,399.262182,-22.915885,11.825623,4.088222,0.485039,1.501178,2.246499,1.792639,0.525619,0.470564,0.984955,0.919283,-0.079108,0.578897,0.441182,9.152406,0.027356,5.723993,0.508077,0.061963,18.304811,3.749030,3.978461,6.508088,14703.037000,0.084005,11.185368,24372.432847,4.458780,84.965068,53.518634,4947.932221,0.671816,0.016180,0.090845,6.288976,0.002600,18103.684159,0.131210,4.812025,83.415955,2.008044,175.294205,0.030112,0.016993,4.035645,91565.399835,0.661378,0.788215,0.384843,0.839815,68.984254,0.014845,1478.179028,0.109309,9.759035,62.870073,124961.546920,1.210532e+07,1361.164718,0.033962,4496.014864,0.332472,0.596553,37.363563,0.022225,5.718917,0.077263,124794.031775,112.356057,0.000048,117.833853,0.039353,0.004477,case_00127
2,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},28f1fe1e69d6329bbf21b39ad7c49f781e1e0695,3D,"(2.5, 0.8789060115814209, 0.8789060115814209)","(206, 512, 512)",-686.470071,-2048.0,1564.0,cc83a4b71370bb2f92b4a1bae4e345913f5ed572,"(2.5, 0.8789060115814209, 0.8789060115814209)","(206, 512, 512)","(55, 201, 126, 46, 136, 276)",254075,22,"(np.float64(76.85642034832235), np.float64(267...","(232.06526401555905, 234.9449382042634, -192.1...",0.358657,0.173283,60.061969,346.612148,235.599873,244.534967,132.203797,248.811557,490646.519305,124.314819,0.384542,78232.364863,0.159448,490666.957726,12.0,215.0,5.974121e+09,3.495346,107.0,2.813391,315.0,63.044186,132.706976,153.0,-139.0,454.0,45.331715,153.340200,-0.770173,1.153716e+10,0.105468,5902.075507,152.724359,1993.186912,-104.824035,25.756194,6.794778,0.579979,1.884191,2.539896,3.166812,0.484493,0.420776,0.982632,0.915847,-0.102855,0.680426,0.404690,12.164645,0.018805,6.440703,0.611494,0.053774,24.329290,4.202703,8.137743,6.754336,23342.457759,0.091872,9.807634,26796.879988,9.524560,149.433770,42.390826,7253.189188,0.297023,0.010414,0.123177,13.960143,0.002347,20386.002187,0.097978,10.145138,145.733114,1.799190,279.370382,0.017006,0.011042,4.364678,146801.620271,0.704174,0.818917,0.302227,0.864485,123.419658,0.009989,2355.150469,0.079671,15.022114,100.866310,83391.367985,1.559791e+07,460.210935,0.021781,10153.254051,0.343468,0.606132,61.158166,0.014375,6.062228,0.116348,83317.495004,100.740495,0.000036,199.404785,0.072847,0.004902,case_00128
3,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},2e2820bc5516d3307df7dfa7aeb12bfc20a2c128,3D,"(5.0, 0.736328125, 0.736328125)","(48, 512, 512)",-425.741773,-1024.0,1247.0,47eee9aefa819c0aeadca27aead9a5c3f86b35ef,"(5.0, 0.736328125, 0.736328125)","(48, 512, 512)","(16, 257, 124, 22, 99, 277)",147945,4,"(np.float64(26.664037311162932), np.float64(30...","(193.9205635170587, 226.90492798210485, -133.3...",0.376646,0.198203,53.259323,268.710792,206.403234,201.180691,117.218138,206.415054,401121.724672,101.208824,0.507492,51828.930365,0.129210,401063.440418,38.0,197.0,3.294651e+09,3.092012,85.0,3.355248,264.0,51.520071,135.111345,158.0,-125.0,389.0,36.256449,149.229454,-1.055089,8.931454e+09,0.150618,4014.354245,127.257270,1015.947725,-70.454882,16.739040,5.788709,0.480220,1.617250,2.360118,2.952584,0.544245,0.495129,0.979743,0.916290,-0.108133,0.573515,0.419379,11.158646,0.038273,5.657573,0.503660,0.112205,22.317291,3.808952,5.631937,6.718700,9940.128217,0.067188,19.221519,22283.161046,6.498393,125.854885,74.824854,11044.989794,0.578407,0.011543,0.094786,8.374077,0.002085,14349.651421,0.128878,7.117882,120.516589,2.441151,326.679910,0.024579,0.012582,4.235524,71019.347997,0.628991,0.751663,0.602125,0.817150,95.066740,0.010970,1281.040529,0.095089,9.779063,78.960659,99454.721571,1.545097e+07,653.283700,0.024938,4336.225653,0.321869,0.584096,44.695322,0.015771,5.883262,0.091061,99334.124590,90.640323,0.000048,140.241457,0.067146,0.005866,case_00129
4,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},0b034ade1281d160ccb8bc159169f4f3e56bad45,3D,"(3.0, 0.546875, 0.546875)","(53, 512, 512)",-351.406944,-1024.0,1420.0,cdfdf27c93d56806e7c17020b97656eb61aebfa3,"(3.0, 0.546875, 0.546875)","(53, 512, 512)","(5, 216, 66, 43, 168, 348)",271936,26,"(np.float64(26.943207225229465), np.float64(30...","(134.38007788367483, 164.73925017053645, -80.8...",0.373239,0.202663,54.486482,268.852606,195.802666,186.164154,112.404977,197.481404,243491.554260,100.346304,0.325678,57900.806162,0.237794,243985.546875,23.0,243.0,6.981270e+09,3.622745,134.0,2.099361,438.0,70.914309,137.314545,134.0,-88.0,526.0,55.595911,160.226326,-0.220392,6.263713e+09,0.089651,6817.191542,113.547390,2400.805006,-35.633315,33.202445,6.936145,0.651665,1.770220,2.459629,3.426215,0.532993,0.479347,0.986653,0.931093,-0.181784,0.777922,0.384841,10.342674,0.018345,6.451007,0.675638,0.053419,20.685349,4.442467,10.034647,7.423715,18803.314633,0.069146,22.640586,24379.411031,10.987563,111.251107,77.511973,9465.375857,0.947700,0.017177,0.092225,7.507812,0.002806,17355.268281,0.084535,11.210488,107.751413,2.673223,309.324179,0.040264,0.018624,4.680003,135934.453153,0.647480,0.753557,0.772110,0.827028,86.809554,0.016296,1928.588295,0.084740,10.931881,71.517026,88525.574234,1.195939e+07,847.696814,0.035546,6533.903643,0.287091,0.549307,37.629677,0.020950,6.313298,0.083692,88382.807489,101.555733,0.000037,277.420495,0.059438,0.006921,case_00130

In [16]:
df2.head()

,diagnostics_Versions_PyRadiomics,diagnostics_Versions_Numpy,diagnostics_Versions_SimpleITK,diagnostics_Versions_PyWavelet,diagnostics_Versions_Python,diagnostics_Configuration_Settings,diagnostics_Configuration_EnabledImageTypes,diagnostics_Image-original_Hash,diagnostics_Image-original_Dimensionality,diagnostics_Image-original_Spacing,diagnostics_Image-original_Size,diagnostics_Image-original_Mean,diagnostics_Image-original_Minimum,diagnostics_Image-original_Maximum,diagnostics_Mask-original_Hash,diagnostics_Mask-original_Spacing,diagnostics_Mask-original_Size,diagnostics_Mask-original_BoundingBox,diagnostics_Mask-original_VoxelNum,diagnostics_Mask-original_VolumeNum,diagnostics_Mask-original_CenterOfMassIndex,diagnostics_Mask-original_CenterOfMass,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,original_shape_Sphericity,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_VoxelVolume,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,original_firstorder_Minimum,original_firstorder_Range,original_firstorder_RobustMeanAbsoluteDeviation,original_firstorder_RootMeanSquared,original_firstorder_Skewness,original_firstorder_TotalEnergy,original_firstorder_Uniformity,original_firstorder_Variance,original_glcm_Autocorrelation,original_glcm_ClusterProminence,original_glcm_ClusterShade,original_glcm_ClusterTendency,original_glcm_Contrast,original_glcm_Correlation,original_glcm_DifferenceAverage,original_glcm_DifferenceEntropy,original_glcm_DifferenceVariance,original_glcm_Id,original_glcm_Idm,original_glcm_Idmn,original_glcm_Idn,original_glcm_Imc1,original_glcm_Imc2,original_glcm_InverseVariance,original_glcm_JointAverage,original_glcm_JointEnergy,original_glcm_JointEntropy,original_glcm_MCC,original_glcm_MaximumProbability,original_glcm_SumAverage,original_glcm_SumEntropy,original_glcm_SumSquares,original_gldm_DependenceEntropy,original_gldm_DependenceNonUniformity,original_gldm_DependenceNonUniformityNormalized,original_gldm_DependenceVariance,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_glrlm_GrayLevelNonUniformity,original_glrlm_GrayLevelNonUniformityNormalized,original_glrlm_GrayLevelVariance,original_glrlm_HighGrayLevelRunEmphasis,original_glrlm_LongRunEmphasis,original_glrlm_LongRunHighGrayLevelEmphasis,original_glrlm_LongRunLowGrayLevelEmphasis,original_glrlm_LowGrayLevelRunEmphasis,original_glrlm_RunEntropy,original_glrlm_RunLengthNonUniformity,original_glrlm_RunLengthNonUniformityNormalized,original_glrlm_RunPercentage,original_glrlm_RunVariance,original_glrlm_ShortRunEmphasis,original_glrlm_ShortRunHighGrayLevelEmphasis,original_glrlm_ShortRunLowGrayLevelEmphasis,original_glszm_GrayLevelNonUniformity,original_glszm_GrayLevelNonUniformityNormalized,original_glszm_GrayLevelVariance,original_glszm_HighGrayLevelZoneEmphasis,original_glszm_LargeAreaEmphasis,original_glszm_LargeAreaHighGrayLevelEmphasis,original_glszm_LargeAreaLowGrayLevelEmphasis,original_glszm_LowGrayLevelZoneEmphasis,original_glszm_SizeZoneNonUniformity,original_glszm_SizeZoneNonUniformityNormalized,original_glszm_SmallAreaEmphasis,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,case_id
0,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},236ac51b094cecd21c8a171a61e8e4e138f6f0ab,3D,"(1.0, 1.0, 1.0)","(72, 512, 512)",-859.200012,-3024.0,3071.0,0da7cedd0a38a672bb8a8acb8629765c360dd627,"(1.0, 1.0, 1.0)","(72, 512, 512)","(50, 354, 222, 1, 15, 19)",270,1,"(np.float64(50.0), np.float64(360.996296296296...","(50.0, 360.9962962962963, 231.43333333333334)",0.829893,0.000000,0.000000,20.785042,19.000000,23.021729,15.000000,23.021729,253.916667,17.249357,0.342635,565.952590,2.228891,270.0,-100.0,11.0,852006.0,2.647453,69.75,2.099668,34.0,35.242798,-38.088889,-29.5,-133.0,167.0,27.927197,56.174530,-0.453359,852006.0,0.175501,1704.814321,27.706804,196.912433,-13.269369,9.636825,0.853611,0.837117,0.657851,1.340722,0.411950,0.702932,0.690651,0.987155,0.929062,-0.333484,0.903354,0.493825,5.050818,0.062244,4.354491,0.856133,0.127942,10.101636,3.478549,2.622609,5.121183,45.577778,0.168807,2.876818,47.385185,2.788765,27.677778,20.392593,610.596296,1.165657,0.073524,0.119761,3.381667,0.012759,26.854453,0.165317,2.900552,26.699096,3.841805,112.120126,0.244103,0.081949,4.157199,69.921428,0.427020,0.601852,1.024504,0.669518,17.471826,0.059816,4.941176,0.145329,4.042388,25.911765,200.294118,6.868853e+03,8.512579,0.130021,5.470588,0.160900,0.361326,11.775212,0.054914,4.631293,0.125926,137.231834,0.545753,0.048838,11.262994,0.046388,1.053216,pXwitKy0oU.hdf5
1,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},d30c6eae8c138dfbb830e7937299e5d5e22d5334,3D,"(1.0, 1.0, 1.0)","(34, 512, 512)",-802.710519,-3024.0,1389.0,5725e9cd036b1b5bd799f78b4d78e215bedf6e25,"(1.0, 1.0, 1.0)","(34, 512, 512)","(4, 354, 265, 9, 73, 75)",31252,1,"(np.float64(8.918053244592347), np.float64(391...","(8.918053244592347, 391.3231473185716, 300.486...",0.966737,0.107577,8.275735,76.928620,75.059976,103.966341,73.006849,103.971150,31175.958333,74.369751,0.400519,11960.274903,0.383638,31252.0,-97.0,22.0,139921014.0,2.636032,42.00,4.981165,213.0,32.071714,-50.722514,-58.0,-461.0,674.0,19.737590,66.911777,1.094102,139921014.0,0.202064,1904.412506,306.467943,495.681840,36.510246,9.954147,1.350324,0.755464,0.742994,1.557708,0.752097,0.702783,0.684504,0.998297,0.975047,-0.268389,0.833056,0.433140,17.444667,0.074566,4.466388,0.863836,0.168875,34.889335,3.438107,2.826118,6.905808,1541.670357,0.049330,30.530706,6314.915333,3.127358,309.045949,164.093946,49302.057084,0.560202,0.003394,0.028737,9.404868,0.000128,3341.747758,0.180169,3.608783,313.414822,5.509048,1683.193685,0.018666,0.003392,4.385747,8779.043473,0.449241,0.593963,2.014765,0.681160,216.351752,0.002309,67.116638,0.115123,8.117274,334.963979,301886.957118,8.729653e+07,1053.890692,0.005104,108.317324,0.185793,0.424484,135.313961,0.003315,6.359380,0.018655,299013.408683,4.345782,0.000346,156.374146,0.006061,0.169227,34jxhEPOGB.hdf5
2,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},c2a689a0c25d0946cba82cab2c08bdb9f7baf825,3D,"(1.0, 1.0, 1.0)","(71, 512, 512)",-899.619642,-2048.0,1716.0,904407d86b2b4d63054e128ce9df5e996a126a74,"(1.0, 1.0, 1.0)","(71, 512, 512)","(47, 321, 298, 3, 23, 27)",1344,1,"(np.float64(48.015625), np.float64(331.84375),...","(48.015625, 331.84375, 311.046875)",0.934873,0.114802,3.020926,26.314124,27.073973,31.144823,23.086793,34.885527,1319.041667,24.600363,0.438604,1326.121810,1.005368,1344.0,-119.0,49.0,7322015.0,2.912997,136.00,1.386178,69.0,62.225403,-30.966518,-38.5,-146.0,215.0,55.484378,73.810079,-0.063336,7322015.0,0.155017,4489.002599,33.930009,738.353044,-15.318582,20.662910,6.834285,0.491238,1.882417,2.279848,2.445046,0.524698,0.463849,0.931864,0.848488,-0.212723,0.745625,0.318857,5.518710,0.044089,5.206324,0.560285,0.121374,11.037420,3.780561,6.874299,6.217547,117.528274,0.087447,11.436382,208.342262,7.249335,34.991815,57.583333,2431.780506,5.790587,0.127481,0.067263,1.759666,0.013046,148.907223,0.140158,7.057183,33.658231,3.310455,123.379218,0.374069,0.133141,3.857800,766.610353,0.676210,0.777186,1.069212,0.825748,26.877154,0.112359,11.813187,0.129815,5.539669,24.285714,2324.219780,1.044489e+05,195.219848,0.223772,13.967033,0.153484,0.377454,7.028229,0.107929,5.399992,0.067708,2106.089603,5.394719,0.004253,37.036862,0.236809,0.159296,VQwDzzw84L.hdf5
3,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},fd3df26e0744d4872f96b33b55854bd71364b992,3D,"(1.0, 1.0, 1.0)","(78, 512, 512)",-617.774033,-2048.0,5093.0,9cc176bda25cae35fd9c8cb7da24fe10d26d4404,"(1.0, 1.0, 1.0)","(78, 512, 512)","(41, 175, 262, 5, 42, 41)",6697,1,"(np.float64(42.994475138121544), np.float64(19...","(42.994475138121544, 195.78453038674033, 282.0...",0.976249,0.129814,5.619874,43.291867,41.012193,55.865911,42.107007,57.393379,6652.333333,42.263640,0.416970,4102.315761,0.616673,6697.0,-65.0,47.0,13443337.0,2.471410,40.00,4.597872,92.0,32.749641,7.849634,22.0,-156.0,248.0,19.118784,44.803650,-1.493282,13443337.0,0.243846,1945.750273,66.082045,442.927511,-42.674430,8.400946,2.527155,0.511859,1.013753,1.853424,1.403000,0.648072,0.619961,0.981393,0.923828,-0.135605,0.563037,0.438613,8.037318,0.092509,4.362926,0.584056,0.217082,16.074637,3.125066,2.732025,6.333938,379.558160,0.056676,26.765482,1633.039122,3.204988,64.475287,112.410184,8195.031955,1.885312,0.024071,0.055490,3.118704,0.001945,919.983766,0.200810,3.619393,61.847846,3.512177,238.376788,0.074832,0.026420,3.888223,2621.432518,0.551264,0.682521,1.092032,0.760689,45.388416,0.021617,44.193333,0.147311,5.479822,54.293333,32617.536667,2.452094e+06,451.339678,0.041301,81.700000,0.272333,0.538930,31.510004,0.020685,5.444215,0.044796,32119.205456,7.648766,0.001115,40.704287,0.043848,0.072230,WooVhg7ysO.hdf5
4,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.13,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},f8c85577efcb9c11b7b479edfb6d2ade3dea70c8,3D,"(1.0, 1.0, 1.0)","(104, 512, 512)",-1037.742660,-3024.0,1590.0,140ba97cbe8ad15ce92495a333b81d8f3075a99f,"(1.0, 1.0, 1.0)","(104, 512, 512)","(27, 173, 299, 17, 57, 61)",35444,1,"(np.float64(35.37289809276605), np.float64(200...","(35.37289809276605, 200.45505586276943, 328.26...",0.922008,0.241127,14.810514,61.422056,61.294372,76.485293,57.870545,81.688432,35381.375000,56.631626,0.608176,8569.810763,0.242212,35444.0,-24.0,64.0,86357537.0,2.392212,33.00,18.993997,784.0,27.349518,28.190921,36.0,-149.0,933.0,15.216716,49.360410,-0.255700,86357537.0,0.255022,1641.722070,61.119863,1281.585960,-12.073288,8.219112,1.800197,0.637976,0.924098,1.726618,0.932558,0.638204,0.611486,0.998776,0.976831,-0.134815,0.667475,0.492462,7.714549,0.085857,4.361852,0.753724,0.192241,15.429098,3.072470,2.504827,6.125369,2124.468570,0.059939,20.662784,9039.000282,2.709747,61.231125,109.734116,7069.882801,2.059742,0.024113,0.047436,2.992184,0.001988,5182.121609,0.216473,3.202742,60.200649,3.117050,195.205780,0.067348,0.026014,3.847193,12813.919572,0.531448,0.675471,0.883752,0.754826,44.825350,0.020809,220.726989,0.172174,11.842529,67.835413,234301.588144,1.548543e+07,3665.258322,0.052296,400.006240,0.312017,0.575594,41.296490,0.031146,5.397994,0.036170,233537.207985,11.187807,0.000221,399.550265,0.004114,0.436908,45Nh52EJwK.hdf5

In [20]:
[i for  i in pd.read_csv('1.csv').columns if i not in df1.columns]

['Unnamed: 0']

In [2]:
pd.read_csv('1.csv').iloc[:,0]

0    3.1.1.dev111+g8ed579383
1    3.1.1.dev111+g8ed579383
2    3.1.1.dev111+g8ed579383
Name: diagnostics_Versions_PyRadiomics, dtype: str

In [26]:
pd.read_csv('2.csv')

,diagnostics_Versions_PyRadiomics,diagnostics_Versions_Numpy,diagnostics_Versions_SimpleITK,diagnostics_Versions_PyWavelet,diagnostics_Versions_Python,diagnostics_Configuration_Settings,diagnostics_Configuration_EnabledImageTypes,diagnostics_Image-original_Hash,diagnostics_Image-original_Dimensionality,diagnostics_Image-original_Spacing,diagnostics_Image-original_Size,diagnostics_Image-original_Mean,diagnostics_Image-original_Minimum,diagnostics_Image-original_Maximum,diagnostics_Mask-original_Hash,diagnostics_Mask-original_Spacing,diagnostics_Mask-original_Size,diagnostics_Mask-original_BoundingBox,diagnostics_Mask-original_VoxelNum,diagnostics_Mask-original_VolumeNum,diagnostics_Mask-original_CenterOfMassIndex,diagnostics_Mask-original_CenterOfMass,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,original_shape_MinorAxisLength,original_shape_Sphericity,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_VoxelVolume,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,original_firstorder_Minimum,original_firstorder_Range,original_firstorder_RobustMeanAbsoluteDeviation,original_firstorder_RootMeanSquared,original_firstorder_Skewness,original_firstorder_TotalEnergy,original_firstorder_Uniformity,original_firstorder_Variance,original_glcm_Autocorrelation,original_glcm_ClusterProminence,original_glcm_ClusterShade,original_glcm_ClusterTendency,original_glcm_Contrast,original_glcm_Correlation,original_glcm_DifferenceAverage,original_glcm_DifferenceEntropy,original_glcm_DifferenceVariance,original_glcm_Id,original_glcm_Idm,original_glcm_Idmn,original_glcm_Idn,original_glcm_Imc1,original_glcm_Imc2,original_glcm_InverseVariance,original_glcm_JointAverage,original_glcm_JointEnergy,original_glcm_JointEntropy,original_glcm_MCC,original_glcm_MaximumProbability,original_glcm_SumAverage,original_glcm_SumEntropy,original_glcm_SumSquares,original_gldm_DependenceEntropy,original_gldm_DependenceNonUniformity,original_gldm_DependenceNonUniformityNormalized,original_gldm_DependenceVariance,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_glrlm_GrayLevelNonUniformity,original_glrlm_GrayLevelNonUniformityNormalized,original_glrlm_GrayLevelVariance,original_glrlm_HighGrayLevelRunEmphasis,original_glrlm_LongRunEmphasis,original_glrlm_LongRunHighGrayLevelEmphasis,original_glrlm_LongRunLowGrayLevelEmphasis,original_glrlm_LowGrayLevelRunEmphasis,original_glrlm_RunEntropy,original_glrlm_RunLengthNonUniformity,original_glrlm_RunLengthNonUniformityNormalized,original_glrlm_RunPercentage,original_glrlm_RunVariance,original_glrlm_ShortRunEmphasis,original_glrlm_ShortRunHighGrayLevelEmphasis,original_glrlm_ShortRunLowGrayLevelEmphasis,original_glszm_GrayLevelNonUniformity,original_glszm_GrayLevelNonUniformityNormalized,original_glszm_GrayLevelVariance,original_glszm_HighGrayLevelZoneEmphasis,original_glszm_LargeAreaEmphasis,original_glszm_LargeAreaHighGrayLevelEmphasis,original_glszm_LargeAreaLowGrayLevelEmphasis,original_glszm_LowGrayLevelZoneEmphasis,original_glszm_SizeZoneNonUniformity,original_glszm_SizeZoneNonUniformityNormalized,original_glszm_SmallAreaEmphasis,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,case_id
0,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},efa3b25548453d2ead4d24e03239e57843455143,3D,"(0.5, 0.7734375, 0.7734375)","(553, 512, 512)",-487.994520,-1024.0,3071.0,3c3f63fd4b216aa93cefc04bb1839a7e721aa06d,"(0.5, 0.7734375, 0.7734375)","(553, 512, 512)","(50, 253, 139, 200, 106, 290)",974874,99,"(np.float64(136.36064147777046), np.float64(31...","(211.3025158491636, 242.03127418581786, -68.18...",0.318793,0.169421,47.403208,279.795996,219.088876,225.250975,106.686914,226.142903,291267.860573,89.197000,0.443912,47868.368299,0.164345,291587.526672,14.0,170.0,1.299409e+10,3.326671,92.0,3.910144,540.0,50.987067,96.880435,104.0,-141.0,681.0,37.403691,115.451245,0.025988,3.886567e+09,0.114965,3943.171266,115.339332,1808.649696,7.793014,21.289536,2.760253,0.770057,1.186048,1.990244,1.319426,0.582576,0.542436,0.996548,0.960796,-0.214640,0.857825,0.476296,10.521720,0.025099,5.860224,0.784450,0.056867,21.043440,4.179225,6.012447,7.123616,71320.221891,0.073158,14.520473,112076.105209,6.393267,114.460249,81.520311,9717.213202,0.827782,0.011734,0.047794,4.997489,0.000880,77697.681414,0.110123,6.884478,113.117313,2.543982,295.446182,0.028269,0.012213,4.544462,411689.996545,0.580366,0.723641,0.608922,0.788956,88.267431,0.009970,2367.734420,0.074940,18.716364,105.765058,1.431722e+06,1.762062e+08,12879.584031,0.023304,7940.697104,0.251328,0.512136,52.320727,0.013177,6.855845,0.032409,1.430770e+06,158.088848,0.000015,286.097236,0.011984,0.007174,case_00053
1,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},e70c94548079c8bc374600cb9bb6be4c8a2e2f9c,3D,"(5.0, 0.9765625, 0.9765625)","(104, 512, 512)",-567.554051,-1024.0,2889.0,ae2e61c83c7b6f5092bcb0a8f672a078a35d4518,"(5.0, 0.9765625, 0.9765625)","(104, 512, 512)","(22, 218, 122, 32, 99, 270)",114367,4,"(np.float64(37.05278620581112), np.float64(268...","(250.83470660789388, 261.90777449187703, -185....",0.321756,0.170492,64.695978,379.467342,256.642257,263.137842,143.899724,270.710385,544479.688009,122.095937,0.421602,76483.810889,0.140471,545344.352722,14.0,133.0,1.005975e+09,2.845318,59.0,3.256037,240.0,36.525891,81.725218,91.0,-134.0,374.0,25.279460,93.787120,-0.767224,4.796862e+09,0.166459,2117.012641,100.484427,254.195279,-19.451806,8.562892,3.648104,0.399351,1.406795,2.175346,1.633107,0.541463,0.490754,0.986508,0.923865,-0.059959,0.479416,0.453421,9.962626,0.037030,5.357092,0.420586,0.088950,19.925252,3.493835,3.052749,6.310467,8999.765605,0.078692,12.659488,19037.422360,3.470261,99.311462,58.094092,6259.620345,0.583149,0.012249,0.096786,8.015276,0.001820,13651.972687,0.153201,3.828802,97.495073,2.071793,211.330885,0.023854,0.012760,3.871176,58227.697820,0.651446,0.779211,0.414272,0.834119,80.076388,0.011000,1212.437013,0.124378,7.973202,75.645261,9.447301e+04,1.052653e+07,874.181577,0.021300,3650.602175,0.374498,0.635127,49.362313,0.014090,5.320130,0.085234,9.433536e+04,70.991167,0.000065,121.187618,0.030295,0.007047,case_00054
2,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},7300ea21ae6fe6c03217d83f86063e9733d29149,3D,"(5.0, 0.87890625, 0.87890625)","(101, 512, 512)",-594.324465,-1024.0,1641.0,00b78ee2a4a4f1e24f6927003c466a09725627ef,"(5.0, 0.87890625, 0.87890625)","(101, 512, 512)","(16, 255, 102, 31, 125, 290)",96137,157,"(np.float64(31.682369951215453), np.float64(31...","(236.56174444575188, 277.6491603047604, -158.4...",0.367577,0.155386,52.223615,336.089992,255.769397,254.952509,168.766275,256.458171,366271.197796,123.538910,0.290359,85261.070752,0.232781,371317.720413,18.0,178.0,1.564802e+09,3.179776,89.0,2.781740,245.0,50.870970,111.815649,127.0,-113.0,358.0,37.347790,127.580548,-0.749423,6.043863e+09,0.129893,3774.056916,108.300793,778.863729,-46.386896,15.989510,5.329546,0.496161,1.603967,2.348962,2.571104,0.536551,0.484431,0.978636,0.911399,-0.108768,0.604421,0.416859,10.277725,0.028967,5.819651,0.513517,0.089577,20.555449,3.904862,5.329764,6.844637,7008.523555,0.072901,17.295310,12487.500369,6.126739,105.987195,64.150650,8024.038372,0.615002,0.013827,0.112531,8.505952,0.002814,8906.788853,0.119335,6.470309,101.862696,2.235340,251.284727,0.027465,0.014858,4.200319,49735.037761,0.657652,0.775189,0.509134,0.834503,82.374918,0.013079,1046.838388,0.100464,8.038181,67.764971,4.074014e+04,5.484979e+06,312.611084,0.027947,3767.677351,0.361581,0.622417,41.117613,0.018804,5.659272,0.108387,4.065502e+04,68.081314,0.000081,115.756636,0.069983,0.007484,case_00055
3,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},2f4768a7cd944a178c4f91894281ab42a7061bf3,3D,"(5.0, 0.78125, 0.78125)","(90, 512, 512)",-286.113787,-1024.0,1294.0,12e50644dea5738094bd2d3478304366733ec0d3,"(5.0, 0.78125, 0.78125)","(90, 512, 512)","(16, 196, 81, 35, 158, 323)",186876,129,"(np.float64(34.4422451251097), np.float64(278....","(223.1515943392945, 217.56251053506065, -172.2...",0.466932,0.259080,70.956479,273.879064,251.229448,252.148967,145.978731,253.271611,565367.126465,127.882860,0.340056,97234.703554,0.171985,570300.292969,21.0,126.0,1.412096e+09,2.787670,54.0,3.364426,248.0,32.848245,76.206517,80.0,-141.0,389.0,22.495072,86.927125,-0.446047,4.309374e+09,0.172178,1748.891869,94.919937,161.018678,-7.756145,6.843128,3.562694,0.311771,1.435036,2.170400,1.484788,0.528188,0.473413,0.986718,0.921965,-0.035785,0.377443,0.450354,9.700419,0.035290,5.341434,0.327379,0.075235,19.400839,3.406982,2.601456,6.169143,16315.762227,0.087308,10.174645,32175.946927,2.882763,94.420113,48.976113,4778.273695,0.536809,0.012421,0.104262,8.997191,0.001835,24122.481456,0.161594,3.175766,93.780655,1.924121,183.389243,0.023033,0.012733,3.739426,101057.421670,0.675363,0.798881,0.350015,0.848200,79.072724,0.011024,2092.270185,0.122412,8.216684,82.378891,1.471437e+05,1.458669e+07,1534.219069,0.019552,6664.818278,0.389938,0.648580,53.680787,0.013417,5.343207,0.091462,1.470242e+05,125.376443,0.000038,121.833573,0.025169,0.004130,case_00056
4,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},18344dae47c5f769ceea34efbad18e268bd79fe9,3D,"(3.0, 0.822265625, 0.822265625)","(80, 512, 512)",-490.761859,-1024.0,1385.0,c52cfc50ab6601fec1bf635c1b9e005bc1479075,"(3.0, 0.822265625, 0.822265625)","(80, 512, 512)","(29, 194, 111, 41, 104, 298)",165022,43,"(np.float64(47.704045521203234), np.float64(25...","(224.99970772126215, 208.51903753031792, -143....",0.269508,0.165025,58.439563,354.126107,245.493845,241.781051,126.134739,247.642134,333607.447716,95.439951,0.339372,68543.423415,0.205461,334724.399208,-1.0,102.0,7.517994e+08,2.685619,56.0,2.728958,237.0,32.178737,54.794615,59.0,-98.0,335.0,23.322027,67.496315,-0.382812,1.524922e+09,0.177427,1553.302711,48.435909,134.127247,-6.359664,6.862974,2.225146,0.507244,1.072353,1.876813,1.035064,0.605726,0.570461,0.989149,0.932955,-0.108619,0.604642,0.477930,6.875684,0.046493,4.922593,0.519962,0.098951,13.751368,3.394197,2.272030,6.516494,10704.055811,0.064864,18.543444,29279.314661,2.566729,47.608834,89.842966,4645.531232,2.010568,0.028490,0.057448,2.158766,0.003068,19500.940345,0.165500,2.844843,46.334725,2.723893,134.087078,0.070628,0.030485,3.938050,68405.044489,0.574157,0.713696,0.701889,0.783342,35.414663,0.025248,1098.035438,0.149088,6.196066,34.305499,2.773953e+05,1.483977e+07,5598.496964,0.066197,2129.915682,0.289194,0.554021,18.714356,0.040863,5.626947,0.044630,2.768932e+05,143.449056,0.000055,68.576675,0.021417,0.004344,case_00057
5,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},44f122a2e16833a16722ccdf1807db41ae22debb,3D,"(5.0, 0.951171875, 0.951171875)","(103, 512, 512)",-528.011458,-1024.0,1295.0,de3bc274fc2819cdfc7dee5104576b6df18f5119,"(5.0, 0.951171875, 0.951171875)","(103, 512, 512)","(16, 206, 131, 32, 145, 271)",141187,35,"(np.float64(31.21324909517165), np.float64(271...","(253.34818299212657, 258.15104617181026, -156....",0.360931,0.156117,55.918663,358.184982,256.865075,256.895658,155.133330,269.382195,639244.193343,129.280160,0.397282,90329.627616,0.141307,638679.115353,5.0,130.0,1.140858e+09,2.891212,63.0,2.899000,271.0,37.925435,76.556383,85.0,-110.0,381.0,26.893582,89.891459,-0.640372,5.160830e+09,0.157813,2219.594594,78.131064,288.703019,-20.555633,9.470390,3.642970,0.441501,1.403186,2.164931,1.617117,0.543064,0.492694,0.986522,0.924075,-0.074101,0.520830,0.452596,8.756248,0.034175,5.430821,0.461726,0.077335,17.512496,3.572717,3.278340,6.443382,11098.548599,0.078609,12.788214,22281.088294,3.634695,77.292612,58.822632,4951.239987,0.800013,0.017034,0.091954,5.941161,0.002532,16152.752379,0.147155,3.939633,75.814248,2.093740,166.330136,0.033285,0.017828,3.915732,71574.462698,0.648769,0.777505,0.421459,0.831946,62.051316,0.015388,1384.342882,0.122400,7.670554,59.308311,1.150543e+05,1.015688e+07,1369.421584,0.031506,3968.416092,0.350877,0.614229,37.343018,0.020719,5.480299,0.080107,1.148985e+05,107.397021,0.000055,103.787576,0.035549,0.004875,case_00058
6,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},e211561fe6b5f532f2b4c374be70b4e503beca37,3D,"(0.5, 0.7890625, 0.7890625)","(738, 512, 512)",-493.514176,-1024.0,3071.0,e90576f9b49e912a7482888a835fb0ed0a761a2c,"(0.5, 0.7890625, 0.7890625)","(738, 512, 512)","(157, 234, 141, 283, 123, 232)",1036366,23,"(np.float64(297.6121225512994), np.float64(296...","(199.80672410856783, 233.6904992119097, -148.8...",0.372967,0.177652,45.760563,257.585699,183.184357,172.811893,111.250817,198.948622,322485.084460,96.071080,0.517146,43975.520374,0.136365,322630.907166,45.0,207.0,2.425946e+10,3.261822,91.0,3.087289,424.0,52.336903,138.939018,156.0,-153.0,577.0,37.946885,152.997368,-0.719443,7.552207e+09,0.127001,4104.144086,178.171261,1503.974584,-75.801811,22.541936,2.705331,0.785397,1.156720,1.977020,1.330384,0.592724,0.554814,0.995420,0.955943,-0.219407,0.858060,0.473562,13.161002,0.030512,5.744225,0.806019,0.081902,26.322005,4.110222,6.311817,7.133993,69965.377909,0.067510,16.887837,131619.648686,6.650951,177.659052,90.888146,16986.789122,0.565169,0.006954,0.048915,7.377582,0.000494,86341.580546,0.117701,7.051094,174.805836,2.739628,497.304768,0.018180,0.007196,4.549187,416314.195746,0.563433,0.707602,0.700613,0.777249,133.958608,0.005757,3075.816956,0.082263,13.989813,138.878657,1.559424e+06,3.165688e+08,8093.662131,0.012220,9951.527414,0.266155,0.527230,70.582567,0.006812,6.566520,0.036078,1.558655e+06,173.751291,0.000013,190.422982,0.017341,0.003534,case_00059
7,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},7e2365e3b50446c1cc0bd064760585381b903af7,3D,"(3.0, 0.833984375, 0.833984375)","(145, 512, 512)",-587.779323,-1024.0,1853.0,b9d304e7d66b8f6dcbe5171dd6bbe4a8e47f40a2,"(3.0, 0.833984375, 0.833984375)","(145, 512, 512)","(30, 216, 147, 34, 122, 242)",140099,43,"(np.float64(46.51490731554115), np.float64(281...","(217.75068976056664, 234.81088757994348, -139....",0.344162,0.210082,56.797001,270.356633,200.761962,202.395482,107.875936,206.741107,291493.293141,93.046362,0.374928,56705.148661,0.194533,292329.146244,17.0,176.0,2.295627e+09,3.089057,80.0,3.037765,322.0,48.597207,113.194477,128.0,-110.0,432.0,35.061341,128.006832,-0.883487,4.790032e+09,0.141212,3572.759358,109.109995,907.940145,-61.732954,16.508888,3.776500,0.624531,1.324545,2.159430,1.944804,0.578315,0.535987,0.989010,0.936009,-0.145955,0.723076,0.442153,10.291891,0.037124,5.547008,0.636050,0.115216,20.583781,3.839931,5.071347,6.869749,8712.762896,0.062190,21.934526,19783.606828,5.795405,106.770798,86.717957,10644.380060,0.833426,0.013524,0.084456,6.347196,0.002127,12791.109253,0.125126,6.297215,102.219339,2.607079,295.155492,0.030984,0.014719,4.293117,61777.230127,0.598922,0.728892,0.674907,0.800187,78.862045,0.012566,1146.097157,0.104753,7.880646,66.161960,9.948509e+04,1.311640e+07,795.784099,0.028631,3569.110959,0.326214,0.589153,38.530974,0.018288,5.767890,0.078095,9.932112e+04,70.398839,0.000068,110.196018,0.045942,0.007487,case_00060
8,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},bda03f5ec121671222b5c746cd6a61e3702cab4d,3D,"(5.0, 0.9765620231628418, 0.9765620231628418)","(29, 512, 512)",-649.295154,-2048.0,1753.0,350fcb4ccf23d184ac6efd7496211d9dca0fa3b6,"(5.0, 0.9765620231628418, 0.9765620231628418)","(29, 512, 512)","(2, 207, 112, 26, 120, 276)",123831,35,"(np.float64(14.58488585249251), np.float64(267...","(251.3054857802639, 260.93904289651823, -72.92...",0.351417,0.168085,56.574831,336.584074,270.303028,260.831654,132.152990,271.468852,588870.665546,118.281526,0.462363,73482.004688,0.124785,590471.644742,5.0,91.0,5.195565e+08,2.355914,40.0,3.260946,163.0,26.042907,55.747050,63.0,-73.0,236.0,17.745159,64.774144,-0.848855,2.477436e+09,0.234696,1087.956133,35.318359,78.040454,-8.378237,4.683843,1.744102,0.453214,0.902685,1.726382,0.884410,0.653697,0.627613,0.983807,0.923747,-0.108361,0.536016,0.462652,5.880648,0.079893,4.294291,0.468670,0.155670,11.761296,3.040600,1.606986,6.379834,6597.269206,0.053276,26.674673,29062.676947,1.823926,34.904886,129.573007,5024.427833,3.825366,0.040739,0.046014,1.172008,0.004230,16432.780413,0.204424,2.138216,33.307245,3.756849,138.177717,0.131631,0.045755,3.880654,41774.167502,0.508238,0.648312,1.200468,0.734910,23.423398,0.036958,815.649956,0.179343,4.519627,22.891821,3.621821e+05,1.439913e+07,9600.705365,0.114793,1162.744063,0.255661,0.518267,11.809115,0.069187,5.511342,0.036727,3.614408e+05,207.956986,0.000065,29.774371,0.028005,0.002370,case_00061
9,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},4480f4611fd19f99a94c3b70089daab2de150471,3D,"(5.0, 0.9765625, 0.9765625)","(86, 512, 512)",-592.624436,-1024.0,1338.0,ee9eb82096094c8cf63a3c3622db7020a3d0afb3,"(5.0, 0.9765625, 0.9765625)","(86, 512, 512)","(21, 294, 155, 25, 94, 228)",99277,5,"(np.float64(32.71434471226971), np.float64(338...","(262.56914641294054, 330.2442577806289, -163.5...",0.375844,0.170290,50.655763,297.467092,222.712383,222.964425,128.111304,223.193598,473132.332166,111.801231,0.519262,56548.323409,0.119519,473389.625549,21.0,115.0,6.547826e+08,2.593388,52.0,3.293829,179.0,30.178611,71.955337,78.0,-90.0,269.0,21.256004,81.212754,-0.701772,3.122247e+09,0.194895,1417.940953,56.677349,117.297806,-7.866713,6.082986,2.492798,0.416844,1.114014,1.932096,1.207400,0.601787,0.565914,0.983930,0.921099,-0.088069,0.539132,0.474355,7.468579,0.050483,4.850448,0.457225,0.111738,14.937158,3.294089,2.143946,6.458759,6361.859393,0.064082,18.586292,19348.631657,2.351663,57.124812,90.348832,5486.387421,1.660841,0.022512,0.071318,3.250868,0.002984,12734.567113,0.179906,2.654940,55.978877,2.705298,158.482226,0.056120,0.023935,3.867214,40731.303710,0.570015,0.712643,0.685562,0.781210,42.938937,0.019697,870.182078,0.138256,5.588001,41.428027,1.351088e+05,8.454210e+06,2288.725065,0.048204,2296.702256,0.364903,0.625273,25.697553,0.032818,5.171367,0.063398,1.348600e+05,112.188283,0.000077,53.467688,0.030363,0.004278,case_00062

In [3]:
[i for  i in pd.read_csv('0.csv').columns if i not in pd.read_csv('CSV-noncon/noncon-E1.csv').columns]

[]

In [7]:
ls = []

In [8]:
for i in os.listdir():
    if i.endswith(".csv"):
        ls.extend(pd.read_csv(i).iloc[:,-1])

In [9]:
ls

['case_00071',
 'case_00072',
 'case_00073',
 'case_00074',
 'case_00075',
 'case_00076',
 'case_00077',
 'case_00078',
 'case_00079',
 'case_00080',
 'case_00081',
 'case_00082',
 'case_00083',
 'case_00084',
 'case_00085',
 'case_00087',
 'case_00088',
 'case_00089',
 'case_00090',
 'case_00091',
 'case_00126',
 'case_00127',
 'case_00129',
 'case_00128',
 'case_00130',
 'case_00126',
 'case_00127',
 'case_00128',
 'case_00129',
 'case_00130',
 'case_00131',
 'case_00132',
 'case_00133',
 'case_00134',
 'case_00135',
 'case_00136',
 'case_00138',
 'case_00139',
 'case_00140',
 'case_00141',
 'case_00142',
 'case_00143',
 'case_00144',
 'case_00145',
 'case_00146',
 'case_00147',
 'case_00148',
 'case_00149',
 'case_00150',
 'case_00151',
 'case_00152',
 'case_00153',
 'case_00154',
 'case_00155',
 'case_00156',
 'case_00157',
 'case_00158',
 'case_00159',
 'case_00180',
 'case_00116',
 'case_00117',
 'case_00489',
 'case_00488',
 'case_00487',
 'case_00486',
 'case_00485',
 'case_00482',
 'case_00483',
 'case_00481',
 'case_00480',
 'case_00479',
 'case_00478',
 'case_00474',
 'case_00475',
 'case_00476',
 'case_00477',
 'case_00468',
 'case_00471',
 'case_00472',
 'case_00473',
 'case_00463',
 'case_00464',
 'case_00465',
 'case_00466',
 'case_00467',
 'case_00462',
 'case_00460',
 'case_00461',
 'case_00260',
 'case_00449',
 'case_00448',
 'case_00447',
 'case_00446',
 'case_00445',
 'case_00444',
 'case_00443',
 'case_00442',
 'case_00441',
 'case_00440',
 'case_00439',
 'case_00438',
 'case_00437',
 'case_00436',
 'case_00435',
 'case_00434',
 'case_00433',
 'case_00432',
 'case_00431',
 'case_00430',
 'case_00408',
 'case_00407',
 'case_00406',
 'case_00405',
 'case_00404',
 'case_00403',
 'case_00402',
 'case_00401',
 'case_00400',
 'case_00284',
 'case_00283',
 'case_00282',
 'case_00281',
 'case_00280',
 'case_00279',
 'case_00278',
 'case_00277',
 'case_00276',
 'case_00275',
 'case_00274',
 'case_00273',
 'case_00272',
 'case_00271',
 'case_00270',
 'case_00269',
 'case_00268',
 'case_00267',
 'case_00266',
 'case_00265',
 'case_00464',
 'case_00263',
 'case_00262',
 'case_00261',
 'case_00051',
 'case_00052',
 'case_00091',
 'case_00053',
 'case_00054',
 'case_00055',
 'case_00056',
 'case_00057',
 'case_00058',
 'case_00059',
 'case_00060',
 'case_00061',
 'case_00062',
 'case_00063',
 'case_00064',
 'case_00065',
 'case_00066',
 'case_00067',
 'case_00068',
 'case_00069',
 'case_00070',
 'case_00116',
 'case_00117',
 'case_00118',
 'case_00119',
 'case_00120',
 'case_00121',
 'case_00122',
 'case_00123',
 'case_00124',
 'case_00125',
 'case_00259',
 'case_00258',
 'case_00257',
 'case_00256',
 'case_00255',
 'case_00254',
 'case_00253',
 'case_00252',
 'case_00251',
 'case_00250',
 'case_00249',
 'case_00248',
 'case_00247',
 'case_00246',
 'case_00245',
 'case_00244',
 'case_00243',
 'case_00242',
 'case_00241',
 'case_00240',
 'case_00239',
 'case_00238',
 'case_00237',
 'case_00236',
 'case_00235',
 'case_00234',
 'case_00233',
 'case_00232',
 'case_00231',
 'case_00230',
 'case_00229',
 'case_00228',
 'case_00227',
 'case_00226',
 'case_00225',
 'case_00224',
 'case_00223',
 'case_00222',
 'case_00221',
 'case_00220',
 'case_00219',
 'case_00218',
 'case_00217',
 'case_00216',
 'case_00215',
 'case_00214',
 'case_00213',
 'case_00212',
 'case_00211',
 'case_00210',
 'case_00209',
 'case_00208',
 'case_00207',
 'case_00206',
 'case_00204',
 'case_00203',
 'case_00202',
 'case_00201',
 'case_00200']

In [11]:
case = ["case_00017","case_00043","case_00137","case_00176","case_00205","case_00469","case_00470","case_00484"]

In [12]:
[i for i in  case if i not in ls]

['case_00017',
 'case_00043',
 'case_00137',
 'case_00176',
 'case_00205',
 'case_00469',
 'case_00470',
 'case_00484']

In [5]:
df_p1 = pd.read_csv("portven-matched-1.csv")

In [6]:

df_p2 = pd.read_csv("portven-matched-2.csv")

In [7]:
df_aml1 = pd.read_csv("kidney-aml.csv")

In [9]:
df_0 = pd.read_csv("0.csv")

In [11]:
df_1 = pd.read_csv("1.csv")

In [12]:
df_2 = pd.read_csv("2.csv")

In [13]:
df_3 = pd.read_csv("3.csv")

In [14]:
df_4 = pd.read_csv("4.csv")

In [15]:
df_5 = pd.read_csv("5.csv")

In [16]:
df_6 = pd.read_csv("6.csv")

In [22]:
df = pd.concat([df_p1,df_p2,df_aml1,df_0,df_1,df_2,df_3,df_4,df_5,df_6], axis = 0, ignore_index= 1)

In [23]:
df.shape

(251, 130)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Columns: 130 entries, diagnostics_Versions_PyRadiomics to case_id
dtypes: float64(110), int64(2), str(18)
memory usage: 440.4 KB

In [25]:
df.head()

,diagnostics_Versions_PyRadiomics,diagnostics_Versions_Numpy,diagnostics_Versions_SimpleITK,diagnostics_Versions_PyWavelet,diagnostics_Versions_Python,diagnostics_Configuration_Settings,diagnostics_Configuration_EnabledImageTypes,diagnostics_Image-original_Hash,diagnostics_Image-original_Dimensionality,diagnostics_Image-original_Spacing,...,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,case_id
0,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},822e9b00b892efdc199d2b736ad7620f1139fc25,3D,"(1.0, 1.0, 1.0)",...,0.022624,5.262253,0.115836,754.763980,0.785292,0.010449,66.320244,0.190350,0.802237,Cwg6Hv9E0n.hdf5
1,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},cac20675bbd341dc19ec45eb69daecb15fb057dd,3D,"(1.0, 1.0, 1.0)",...,0.061240,4.826605,0.044276,9447.413444,3.306997,0.004428,26.158908,0.023077,0.169821,1a7jTnjpn9.hdf5
2,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},e1576dcee600f14668bf5fc0f5bf4bd967f937d4,3D,"(1.0, 1.0, 1.0)",...,0.012783,5.397547,0.026264,9553.239587,1.407991,0.006793,35.138042,0.033479,0.483916,flGZ1oVmQ3.hdf5
3,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},de62a3c31266b5017b6b9a92416a58c6c491528a,3D,"(1.0, 1.0, 1.0)",...,0.005123,6.894801,0.071782,13971.402315,3.076425,0.000826,225.206801,0.032853,0.199231,qhveYUigqX.hdf5
4,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},42bf21de5964f3604abd8f35020f6fa7a46bedd1,3D,"(1.0, 1.0, 1.0)",...,0.008818,6.160009,0.048050,33723.820010,5.948834,0.000811,84.155835,0.027600,0.098459,nSIvfJZBlK.hdf5

In [29]:
df_p1.shape

(3, 130)

In [30]:
df_p2.shape

(8, 130)

In [31]:
df_aml1.shape

(8, 130)

In [33]:
df

,diagnostics_Versions_PyRadiomics,diagnostics_Versions_Numpy,diagnostics_Versions_SimpleITK,diagnostics_Versions_PyWavelet,diagnostics_Versions_Python,diagnostics_Configuration_Settings,diagnostics_Configuration_EnabledImageTypes,diagnostics_Image-original_Hash,diagnostics_Image-original_Dimensionality,diagnostics_Image-original_Spacing,...,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,case_id
0,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},822e9b00b892efdc199d2b736ad7620f1139fc25,3D,"(1.0, 1.0, 1.0)",...,0.022624,5.262253,0.115836,754.763980,0.785292,0.010449,66.320244,0.190350,0.802237,Cwg6Hv9E0n.hdf5
1,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},cac20675bbd341dc19ec45eb69daecb15fb057dd,3D,"(1.0, 1.0, 1.0)",...,0.061240,4.826605,0.044276,9447.413444,3.306997,0.004428,26.158908,0.023077,0.169821,1a7jTnjpn9.hdf5
2,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},e1576dcee600f14668bf5fc0f5bf4bd967f937d4,3D,"(1.0, 1.0, 1.0)",...,0.012783,5.397547,0.026264,9553.239587,1.407991,0.006793,35.138042,0.033479,0.483916,flGZ1oVmQ3.hdf5
3,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},de62a3c31266b5017b6b9a92416a58c6c491528a,3D,"(1.0, 1.0, 1.0)",...,0.005123,6.894801,0.071782,13971.402315,3.076425,0.000826,225.206801,0.032853,0.199231,qhveYUigqX.hdf5
4,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},42bf21de5964f3604abd8f35020f6fa7a46bedd1,3D,"(1.0, 1.0, 1.0)",...,0.008818,6.160009,0.048050,33723.820010,5.948834,0.000811,84.155835,0.027600,0.098459,nSIvfJZBlK.hdf5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},4c671441a38f12c6f2562bac888fcee3371277d0,3D,"(3.0, 0.875, 0.875)",...,0.037179,5.749599,0.052300,246231.551629,153.527424,0.000049,69.187975,0.028420,0.003495,case_00204
247,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},76b4ad9ef23886099e88d77e049ce8625483dc75,3D,"(1.0, 0.63671875, 0.63671875)",...,0.017398,6.622344,0.037244,510277.669778,115.970733,0.000035,108.913761,0.031714,0.004701,case_00203
248,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},e3975ea225ac8f6556c25d2413241727759e3b77,3D,"(1.25, 0.8984379768371582, 0.8984379768371582)",...,0.010494,6.313396,0.085239,109821.163040,77.210679,0.000037,216.684985,0.065291,0.006853,case_00202
249,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},af698dfcdabded624a861ac24e16fc6022e5f159,3D,"(2.5, 0.78125, 0.78125)",...,0.012961,6.071012,0.086707,173751.636493,122.905543,0.000025,218.927794,0.039721,0.004232,case_00201
250,3.1.1.dev111+g8ed579383,2.0.2,2.5.3,1.8.0,3.12.12,"{'minimumROIDimensions': 2, 'minimumROISize': ...",{'Original': {}},13f009edeae6962f20a36d3ef620f97b278e96f1,3D,"(4.0, 0.7421875, 0.7421875)",...,0.015669,6.005999,0.076375,117797.476297,82.918136,0.000058,107.187897,0.052327,0.006246,case_00200

In [34]:
"case_2763".startswith("case")

True

In [35]:
[ "kits23" if i.startswith("case") else "ucsf-rmac-dataset" for i in df.case_id]

['ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'ucsf-rmac-dataset',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23',
 'kits23']

In [36]:
df["data_source"] = [ "kits23" if i.startswith("case") else "ucsf-rmac-dataset" for i in df.case_id]

/tmp/ipykernel_17702/3905411734.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["data_source"] = [ "kits23" if i.startswith("case") else "ucsf-rmac-dataset" for i in df.case_id]

In [41]:
pd.set_option.display.max_columns

AttributeError: 'function' object has no attribute 'display'

In [48]:
df.iloc[:,-2:]

             case_id        data_source
0    Cwg6Hv9E0n.hdf5  ucsf-rmac-dataset
1    1a7jTnjpn9.hdf5  ucsf-rmac-dataset
2    flGZ1oVmQ3.hdf5  ucsf-rmac-dataset
3    qhveYUigqX.hdf5  ucsf-rmac-dataset
4    nSIvfJZBlK.hdf5  ucsf-rmac-dataset
..               ...                ...
246       case_00204             kits23
247       case_00203             kits23
248       case_00202             kits23
249       case_00201             kits23
250       case_00200             kits23

[251 rows x 2 columns]

In [61]:
ls =  [] 
index = []
for i in df_p1.select_dtypes(include=[np.number]):
    ls.append([df_p1[i].mean(),df_p2[i].mean(),df_aml1[i].mean()])
    index.append(i)
df_mean = pd.DataFrame(data=ls,columns = ["df_p1","df_p2","df_aml1"],index=index)

In [63]:
df_mean.to_dict()

{'df_p1': {'diagnostics_Image-original_Mean': -605.525496592276,
  'diagnostics_Image-original_Minimum': -1692.6404398132836,
  'diagnostics_Image-original_Maximum': 1329.205351447237,
  'diagnostics_Mask-original_VoxelNum': 1517.3333333333333,
  'diagnostics_Mask-original_VolumeNum': 1.0,
  'original_shape_Elongation': 0.8643480805451694,
  'original_shape_Flatness': 0.13917261862921523,
  'original_shape_LeastAxisLength': 3.570838458533018,
  'original_shape_MajorAxisLength': 26.09624135947803,
  'original_shape_Maximum2DDiameterColumn': 21.67390962214756,
  'original_shape_Maximum2DDiameterRow': 31.98401143530786,
  'original_shape_Maximum2DDiameterSlice': 25.371918704054536,
  'original_shape_Maximum3DDiameter': 32.06160100918313,
  'original_shape_MeshVolume': 1493.7083333333333,
  'original_shape_MinorAxisLength': 22.06276928856109,
  'original_shape_Sphericity': 0.5004337768881867,
  'original_shape_SurfaceArea': 1244.8963492613166,
  'original_shape_SurfaceVolumeRatio': 0.8858147695632677,
  'original_shape_VoxelVolume': 1517.3333333333333,
  'original_firstorder_10Percentile': 24.51400225368668,
  'original_firstorder_90Percentile': 169.77607581758227,
  'original_firstorder_Energy': 22521577.14419369,
  'original_firstorder_Entropy': 2.8022604598943883,
  'original_firstorder_InterquartileRange': 77.48777418044587,
  'original_firstorder_Kurtosis': 3.009327901154347,
  'original_firstorder_Maximum': 214.87559701039876,
  'original_firstorder_MeanAbsoluteDeviation': 46.207958128986625,
  'original_firstorder_Mean': 101.50911764402797,
  'original_firstorder_Median': 110.59087554644861,
  'original_firstorder_Minimum': -57.541002674412546,
  'original_firstorder_Range': 272.41659968481133,
  'original_firstorder_RobustMeanAbsoluteDeviation': 33.77413024914361,
  'original_firstorder_RootMeanSquared': 119.4592542099465,
  'original_firstorder_Skewness': -0.1335931626706967,
  'original_firstorder_TotalEnergy': 22521577.14419369,
  'original_firstorder_Uniformity': 0.19301615356912594,
  'original_firstorder_Variance': 3591.345662684951,
  'original_glcm_Autocorrelation': 58.73946185473446,
  'original_glcm_ClusterProminence': 1270.5030841277003,
  'original_glcm_ClusterShade': -45.81863039087466,
  'original_glcm_ClusterTendency': 16.708608761083564,
  'original_glcm_Contrast': 3.3203511020062444,
  'original_glcm_Correlation': 0.6371571527042293,
  'original_glcm_DifferenceAverage': 1.123176544259113,
  'original_glcm_DifferenceEntropy': 1.8676301695093551,
  'original_glcm_DifferenceVariance': 1.696981037798832,
  'original_glcm_Id': 0.634674530781884,
  'original_glcm_Idm': 0.603434082660269,
  'original_glcm_Idmn': 0.9791973465824846,
  'original_glcm_Idn': 0.9211477690308509,
  'original_glcm_Imc1': -0.22535483968731707,
  'original_glcm_Imc2': 0.7684790428883036,
  'original_glcm_InverseVariance': 0.42854862887181167,
  'original_glcm_JointAverage': 7.314305440359281,
  'original_glcm_JointEnergy': 0.07206334778316177,
  'original_glcm_JointEntropy': 4.717882059765407,
  'original_glcm_MCC': 0.7351320691492885,
  'original_glcm_MaximumProbability': 0.17613560642684004,
  'original_glcm_SumAverage': 14.628610880718561,
  'original_glcm_SumEntropy': 3.507651158510645,
  'original_glcm_SumSquares': 5.007239965772453,
  'original_gldm_DependenceEntropy': 6.304354468206146,
  'original_gldm_DependenceNonUniformity': 101.81495217650404,
  'original_gldm_DependenceNonUniformityNormalized': 0.06976929479803144,
  'original_gldm_DependenceVariance': 19.81920556881658,
  'original_gldm_GrayLevelNonUniformity': 301.61943310900307,
  'original_gldm_GrayLevelVariance': 5.816464951123102,
  'original_gldm_HighGrayLevelEmphasis': 59.56351526347722,
  'original_gldm_LargeDependenceEmphasis': 89.83779376581715,
  'original_gldm_LargeDependenceHighGrayLevelEmphasis': 5627.225024195414,
  'original_gldm_LargeDependenceLowGrayLevelEmphasis': 2.3977556411240855,
  'original_gldm_LowGrayLevelEmphasis': 0.0385813882895411,
  'original_gldm_SmallDependenceEmphasis': 0.0634813528016483,
  'original_gldm_SmallDependenceHighGrayLevelEmphasis': 2.9544881032080084,
  'original_gldm_SmallDependenceLowGrayLevelEmphasis': 0.0038554378202323002,
  'original_glrlm_GrayLevelNonUniformity': 185.69365521223529,
  'original_glrlm_GrayLevelNonUniformityNormalized': 0.16461892231503858,
  'original_glrlm_GrayLevelVariance': 6.099699532760077,
  'original_glrlm_HighGrayLevelRunEmphasis': 57.73256953782754,
  'original_glrlm_LongRunEmphasis': 3.1766012790802436,
  'original_glrlm_LongRunHighGrayLevelEmphasis': 191.4166615966332,
  'original_glrlm_LongRunLowGrayLevelEmphasis': 0.10356754445378784,
  'original_glrlm_LowGrayLevelRunEmphasis': 0.0417973580571581,
  'original_glrlm_RunEntropy': 4.010322903116125,
  'original_glrlm_RunLengthNonUniformity': 623.543024085379,
  'original_glrlm_RunLengthNonUniformityNormalized': 0.579336173381228,
  'original_glrlm_RunPercentage': 0.719509255119647,
  'original_glrlm_RunVariance': 0.9180823250454063,
  'original_glrlm_ShortRunEmphasis': 0.7777140770879422,
  'original_glrlm_ShortRunHighGrayLevelEmphasis': 44.031762409733055,
  'original_glrlm_ShortRunLowGrayLevelEmphasis': 0.034840193606436635,
  'original_glszm_GrayLevelNonUniformity': 9.815874143933703,
  'original_glszm_GrayLevelNonUniformityNormalized': 0.13354562449758964,
  'original_glszm_GrayLevelVariance': 6.8197237490412626,
  'original_glszm_HighGrayLevelZoneEmphasis': 41.93882439063225,
  'original_glszm_LargeAreaEmphasis': 7263.261488812644,
  'original_glszm_LargeAreaHighGrayLevelEmphasis': 332465.5530397028,
  'original_glszm_LargeAreaLowGrayLevelEmphasis': 198.62355956797487,
  'original_glszm_LowGrayLevelZoneEmphasis': 0.0786472935109928,
  'original_glszm_SizeZoneNonUniformity': 14.69195399620583,
  'original_glszm_SizeZoneNonUniformityNormalized': 0.1938760937465532,
  'original_glszm_SmallAreaEmphasis': 0.42595378898966113,
  'original_glszm_SmallAreaHighGrayLevelEmphasis': 15.890959951584174,
  'original_glszm_SmallAreaLowGrayLevelEmphasis': 0.0322155758397338,
  'original_glszm_ZoneEntropy': 5.162135036273331,
  'original_glszm_ZonePercentage': 0.0621252874544282,
  'original_glszm_ZoneVariance': 6585.139003850461,
  'original_ngtdm_Busyness': 1.8334265555022455,
  'original_ngtdm_Coarseness': 0.0072237022552897,
  'original_ngtdm_Complexity': 42.53906478293958,
  'original_ngtdm_Contrast': 0.08230165336611349,
  'original_ngtdm_Strength': 0.4853245714466781},
 'df_p2': {'diagnostics_Image-original_Mean': -779.5032710356463,
  'diagnostics_Image-original_Minimum': -2402.0,
  'diagnostics_Image-original_Maximum': 2150.3568550846517,
  'diagnostics_Mask-original_VoxelNum': 23994.0,
  'diagnostics_Mask-original_VolumeNum': 1.0,
  'original_shape_Elongation': 0.9192598443271768,
  'original_shape_Flatness': 0.2019385975941409,
  'original_shape_LeastAxisLength': 9.937502877781593,
  'original_shape_MajorAxisLength': 50.17340481900533,
  'original_shape_Maximum2DDiameterColumn': 45.08159702349218,
  'original_shape_Maximum2DDiameterRow': 62.9298161995545,
  'original_shape_Maximum2DDiameterSlice': 49.17397139849824,
  'original_shape_Maximum3DDiameter': 64.83516462283706,
  'original_shape_MeshVolume': 23942.82291666667,
  'original_shape_MinorAxisLength': 44.670117825707536,
  'original_shape_Sphericity': 0.4866201676040959,
  'original_shape_SurfaceArea': 6764.25506112825,
  'original_shape_SurfaceVolumeRatio': 0.5890904078017154,
  'original_shape_VoxelVolume': 23994.0,
  'original_firstorder_10Percentile': -1.4778425815487424,
  'original_firstorder_90Percentile': 157.22979949864248,
  'original_firstorder_Energy': 269666655.98300093,
  'original_firstorder_Entropy': 3.1728536123107265,
  'original_firstorder_InterquartileRange': 69.68101182467618,
  'original_firstorder_Kurtosis': 4.3118536270274666,
  'original_firstorder_Maximum': 253.07327434515898,
  'original_firstorder_MeanAbsoluteDeviation': 46.52746851457512,
  'original_firstorder_Mean': 79.2300595567824,
  'original_firstorder_Median': 80.6760456374748,
  'original_firstorder_Minimum': -244.09602479708548,
  'original_firstorder_Range': 497.1692991422444,
  'original_firstorder_RobustMeanAbsoluteDeviation': 30.6584505964708,
  'original_firstorder_RootMeanSquared': 116.27604588193773,
  'original_firstorder_Skewness': -0.5413296514571913,
  'original_firstorder_TotalEnergy': 269666655.98300093,
  'original_firstorder_Uniformity': 0.14057057957867664,
  'original_firstorder_Variance': 3929.5599839539454,
  'original_glcm_Autocorrelation': 268.9900736272439,
  'original_glcm_ClusterProminence': 2148.0818646738912,
  'original_glcm_ClusterShade': -33.927076919587705,
  'original_glcm_ClusterTendency': 20.382383802873147,
  'original_glcm_Contrast': 2.6858884734537263,
  'original_glcm_Correlation': 0.7395194890904802,
  'original_glcm_DifferenceAverage': 1.1376671335850024,
  'original_glcm_DifferenceEntropy': 1.916959216988094,
  'original_glcm_DifferenceVariance': 1.270242595389286,
  'original_glcm_Id': 0.6012311405793574,
  'original_glcm_Idm': 0.5637300125967777,
  'original_glcm_Idmn': 0.9913024872760066,
  'original_glcm_Idn': 0.9440708728295767,
  'original_glcm_Imc1': -0.23013569336128292,
  'original_glcm_Imc2': 0.8389337014770731,
  'original_glcm_InverseVariance': 0.4598752253738474,
  'original_glcm_JointAverage': 14.07878301551228,
  'original_glcm_JointEnergy': 0.0405136265000764,
  'original_glcm_JointEntropy': 5.45131383232196,
  'original_glcm_MCC': 0.7905883724958167,
  'original_glcm_MaximumProbability': 0.09760930341013904,
  'original_glcm_SumAverage': 28.157566031024558,
  'original_glcm_SumEntropy': 3.9312435129887984,
  'original_glcm_SumSquares': 5.767068069081719,
  'original_gldm_DependenceEntropy': 6.818528568560593,
  'original_gldm_DependenceNonUniformity': 1780.894014269336,
  'original_gldm_DependenceNonUniformityNormalized': 0.07527904183231877,
  'original_gldm_DependenceVariance': 16.736213661579562,
  'original_gldm_GrayLevelNonUniformity': 2914.7798773853483,
  'original_gldm_GrayLevelVariance': 6.389424842966686,
  'original_gldm_HighGrayLevelEmphasis': 270.27826244492593,
  'original_gldm_LargeDependenceEmphasis': 78.69763194345117,
  'original_gldm_LargeDependenceHighGrayLevelEmphasis': 19782.836537390707,
  'original_gldm_LargeDependenceLowGrayLevelEmphasis': 0.934438493744468,
  'original_gldm_LowGrayLevelEmphasis': 0.016469335151940538,
  'original_gldm_SmallDependenceEmphasis': 0.06244861182021326,
  'original_gldm_SmallDependenceHighGrayLevelEmphasis': 17.34402676137323,
  'original_gldm_SmallDependenceLowGrayLevelEmphasis': 0.0016293233693744002,
  'original_glrlm_GrayLevelNonUniformity': 2014.9953352621444,
  'original_glrlm_GrayLevelNonUniformityNormalized': 0.12898495044829472,
  'original_glrlm_GrayLevelVariance': 6.911724489237891,
  'original_glrlm_HighGrayLevelRunEmphasis': 269.51920714863604,
  'original_glrlm_LongRunEmphasis': 2.710326351466592,
  'original_glrlm_LongRunHighGrayLevelEmphasis': 666.0201447878273,
  'original_glrlm_LongRunLowGrayLevelEmphasis': 0.04088099643708264,
  'original_glrlm_LowGrayLevelRunEmphasis': 0.01776437278934926,
  'original_glrlm_RunEntropy': 4.322908450207596,
  'original_glrlm_RunLengthNonUniformity': 10583.159039995793,
  'original_glrlm_RunLengthNonUniformityNormalized': 0.6074437740264936,
  'original_glrlm_RunPercentage': 0.7396371983690704,
  'original_glrlm_RunVariance': 0.6974642031374754,
  'original_glrlm_ShortRunEmphasis': 0.799497016433059,
  'original_glrlm_ShortRunHighGrayLevelEmphasis': 217.12084678498906,
  'original_glrlm_ShortRunLowGrayLevelEmphasis': 0.014938956254280124,
  'original_glszm_GrayLevelNonUniformity': 90.26325776890755,
  'original_glszm_GrayLevelNonUniformityNormalized': 0.09565786282355379,
  'original_glszm_GrayLevelVariance': 13.74268051277614,
  'original_glszm_HighGrayLevelZoneEmphasis': 253.8764648428437,
  'original_glszm_LargeAreaEmphasis': 54735.51906294109,
  'original_glszm_LargeAreaHighGrayLevelEmphasis': 31452207.32351045,
  'original_glszm_LargeAreaLowGrayLevelEmphasis': 180.30957557363993,
  'original_glszm_LowGrayLevelZoneEmphasis': 0.0345654205522621,
  'original_glszm_SizeZoneNonUniformity': 310.5154481106805,
  'original_glszm_SizeZoneNonUniformityNormalized': 0.22061418009333195,
  'original_glszm_SmallAreaEmphasis': 0.4658001016541287,
  'original_glszm_SmallAreaHighGrayLevelEmphasis': 135.61941766814425,
  'original_glszm_SmallAreaLowGrayLevelEmphasis': 0.014270387405053538,
  'original_glszm_ZoneEntropy': 6.074659488617856,
  'original_glszm_ZonePercentage': 0.053294330892807516,
  'original_glszm_ZoneVariance': 54248.779087270144,
  'original_ngtdm_Busyness': 3.1924244034644054,
  'original_ngtdm_Coarseness': 0.0032692861334182753,
  'original_ngtdm_Complexity': 243.15582171178093,
  'original_ngtdm_Contrast': 0.03201257958618165,
  'original_ngtdm_Strength': 0.3068158734481006},
 'df_aml1': {'diagnostics_Image-original_Mean': -508.5437465087673,
  'diagnostics_Image-original_Minimum': -1152.0,
  'diagnostics_Image-original_Maximum': 1819.375,
  'diagnostics_Mask-original_VoxelNum': 143498.25,
  'diagnostics_Mask-original_VolumeNum': 9.25,
  'original_shape_Elongation': 0.33793759692017766,
  'original_shape_Flatness': 0.18637302036741307,
  'original_shape_LeastAxisLength': 55.16542731150323,
  'original_shape_MajorAxisLength': 298.3055491092443,
  'original_shape_Maximum2DDiameterColumn': 215.2019443753948,
  'original_shape_Maximum2DDiameterRow': 210.09988449456836,
  'original_shape_Maximum2DDiameterSlice': 118.43157570398668,
  'original_shape_Maximum3DDiameter': 223.88478140857745,
  'original_shape_MeshVolume': 363319.480208451,
  'original_shape_MinorAxisLength': 99.84106790072116,
  'original_shape_Sphericity': 0.4352459665046734,
  'original_shape_SurfaceArea': 57147.83036375763,
  'original_shape_SurfaceVolumeRatio': 0.1623042624026237,
  'original_shape_VoxelVolume': 363325.4749852702,
  'original_firstorder_10Percentile': 23.25,
  'original_firstorder_90Percentile': 161.125,
  'original_firstorder_Energy': 2313837859.25,
  'original_firstorder_Entropy': 2.937798970347038,
  'original_firstorder_InterquartileRange': 70.625,
  'original_firstorder_Kurtosis': 3.3376470470468953,
  'original_firstorder_Maximum': 307.125,
  'original_firstorder_MeanAbsoluteDeviation': 43.19177388456589,
  'original_firstorder_Mean': 104.775852695996,
  'original_firstorder_Median': 118.75,
  'original_firstorder_Minimum': -98.5,
  'original_firstorder_Range': 405.625,
  'original_firstorder_RobustMeanAbsoluteDeviation': 30.197843894529253,
  'original_firstorder_RootMeanSquared': 118.00045283362472,
  'original_firstorder_Skewness': -0.8882381687560341,
  'original_firstorder_TotalEnergy': 5255694979.7354965,
  'original_firstorder_Uniformity': 0.1618138165907515,
  'original_firstorder_Variance': 2997.017569696817,
  'original_glcm_Autocorrelation': 90.469657419171,
  'original_glcm_ClusterProminence': 738.9305998036074,
  'original_glcm_ClusterShade': -46.41190075412146,
  'original_glcm_ClusterTendency': 13.301834772934487,
  'original_glcm_Contrast': 3.9478963551259447,
  'original_glcm_Correlation': 0.5251153483267226,
  'original_glcm_DifferenceAverage': 1.319854672104531,
  'original_glcm_DifferenceEntropy': 2.118564672110249,
  'original_glcm_DifferenceVariance': 1.99825292926724,
  'original_glcm_Id': 0.5864152324058809,
  'original_glcm_Idm': 0.5451178576786572,
  'original_glcm_Idmn': 0.9867024064181208,
  'original_glcm_Idn': 0.9318120660543958,
  'original_glcm_Imc1': -0.12874017542817512,
  'original_glcm_Imc2': 0.6312906473556563,
  'original_glcm_InverseVariance': 0.431925901967968,
  'original_glcm_JointAverage': 9.278866714602781,
  'original_glcm_JointEnergy': 0.04576252514871005,
  'original_glcm_JointEntropy': 5.328341695693583,
  'original_glcm_MCC': 0.5486052512130792,
  'original_glcm_MaximumProbability': 0.11210761280870563,
  'original_glcm_SumAverage': 18.557733429205562,
  'original_glcm_SumEntropy': 3.6610917333495814,
  'original_glcm_SumSquares': 4.312432782015108,
  'original_gldm_DependenceEntropy': 6.776015294621823,
  'original_gldm_DependenceNonUniformity': 8620.921955693979,
  'original_gldm_DependenceNonUniformityNormalized': 0.06338181568650593,
  'original_gldm_DependenceVariance': 22.762665648252717,
  'original_gldm_GrayLevelNonUniformity': 23463.43120564862,
  'original_gldm_GrayLevelVariance': 4.8783170312795665,
  'original_gldm_HighGrayLevelEmphasis': 89.42239165068582,
  'original_gldm_LargeDependenceEmphasis': 96.69339593169897,
  'original_gldm_LargeDependenceHighGrayLevelEmphasis': 9624.10272042574,
  'original_gldm_LargeDependenceLowGrayLevelEmphasis': 1.2494800272407853,
  'original_gldm_LowGrayLevelEmphasis': 0.018128877700562276,
  'original_gldm_SmallDependenceEmphasis': 0.0785489706531495,
  'original_gldm_SmallDependenceHighGrayLevelEmphasis': 5.20787782447647,
  'original_gldm_SmallDependenceLowGrayLevelEmphasis': 0.0027510488195885627,
  'original_glrlm_GrayLevelNonUniformity': 14075.128179798703,
  'original_glrlm_GrayLevelNonUniformityNormalized': 0.1426851194755694,
  'original_glrlm_GrayLevelVariance': 5.375759213503011,
  'original_glrlm_HighGrayLevelRunEmphasis': 85.52058983357884,
  'original_glrlm_LongRunEmphasis': 3.020808793457034,
  'original_glrlm_LongRunHighGrayLevelEmphasis': 283.0947513732888,
  'original_glrlm_LongRunLowGrayLevelEmphasis': 0.04713954273783295,
  'original_glrlm_LowGrayLevelRunEmphasis': 0.020038381303410874,
  'original_glrlm_RunEntropy': 4.207960713675853,
  'original_glrlm_RunLengthNonUniformity': 58593.42232082723,
  'original_glrlm_RunLengthNonUniformityNormalized': 0.5882558440775741,
  'original_glrlm_RunPercentage': 0.7143862503291483,
  'original_glrlm_RunVariance': 0.8973931770881219,
  'original_glrlm_ShortRunEmphasis': 0.7897350390500733,
  'original_glrlm_ShortRunHighGrayLevelEmphasis': 65.41855926008529,
  'original_glrlm_ShortRunLowGrayLevelEmphasis': 0.01697310737127746,
  'original_glszm_GrayLevelNonUniformity': 1059.8953402842026,
  'original_glszm_GrayLevelNonUniformityNormalized': 0.11264053571596042,
  'original_glszm_GrayLevelVariance': 7.794027792432301,
  'original_glszm_HighGrayLevelZoneEmphasis': 57.32270838043786,
  'original_glszm_LargeAreaEmphasis': 166424.8211408004,
  'original_glszm_LargeAreaHighGrayLevelEmphasis': 16648825.069431966,
  'original_glszm_LargeAreaLowGrayLevelEmphasis': 1945.5979323938354,
  'original_glszm_LowGrayLevelZoneEmphasis': 0.04236411121722004,
  'original_glszm_SizeZoneNonUniformity': 3024.921697539984,
  'original_glszm_SizeZoneNonUniformityNormalized': 0.31213056264540073,
  'original_glszm_SmallAreaEmphasis': 0.5742753974889747,
  'original_glszm_SmallAreaHighGrayLevelEmphasis': 32.21294393697635,
  'original_glszm_SmallAreaLowGrayLevelEmphasis': 0.026886241728350677,
  'original_glszm_ZoneEntropy': 5.781767274966236,
  'original_glszm_ZonePercentage': 0.07166220496707225,
  'original_glszm_ZoneVariance': 166191.30878265278,
  'original_ngtdm_Busyness': 88.76822759796723,
  'original_ngtdm_Coarseness': 6.537011198805192e-05,
  'original_ngtdm_Complexity': 156.51555709208208,
  'original_ngtdm_Contrast': 0.038814008531623735,
  'original_ngtdm_Strength': 0.009973170642945738}}

In [ ]:
df.select_dtypes(include=[np.number])

In [ ]:
df_p1for i in df_p1.select_dtypes(include=[np.number]).columns

In [58]:
for i in df_p1.select_dtypes(include=[np.number]):
    print({i}, df_p1[i].mean())

{'diagnostics_Image-original_Mean'} -605.525496592276
{'diagnostics_Image-original_Minimum'} -1692.6404398132836
{'diagnostics_Image-original_Maximum'} 1329.205351447237
{'diagnostics_Mask-original_VoxelNum'} 1517.3333333333333
{'diagnostics_Mask-original_VolumeNum'} 1.0
{'original_shape_Elongation'} 0.8643480805451694
{'original_shape_Flatness'} 0.13917261862921523
{'original_shape_LeastAxisLength'} 3.570838458533018
{'original_shape_MajorAxisLength'} 26.09624135947803
{'original_shape_Maximum2DDiameterColumn'} 21.67390962214756
{'original_shape_Maximum2DDiameterRow'} 31.98401143530786
{'original_shape_Maximum2DDiameterSlice'} 25.371918704054536
{'original_shape_Maximum3DDiameter'} 32.06160100918313
{'original_shape_MeshVolume'} 1493.7083333333333
{'original_shape_MinorAxisLength'} 22.06276928856109
{'original_shape_Sphericity'} 0.5004337768881867
{'original_shape_SurfaceArea'} 1244.8963492613166
{'original_shape_SurfaceVolumeRatio'} 0.8858147695632677
{'original_shape_VoxelVolume'} 1517.3333333333333
{'original_firstorder_10Percentile'} 24.51400225368668
{'original_firstorder_90Percentile'} 169.77607581758227
{'original_firstorder_Energy'} 22521577.14419369
{'original_firstorder_Entropy'} 2.8022604598943883
{'original_firstorder_InterquartileRange'} 77.48777418044587
{'original_firstorder_Kurtosis'} 3.009327901154347
{'original_firstorder_Maximum'} 214.87559701039876
{'original_firstorder_MeanAbsoluteDeviation'} 46.207958128986625
{'original_firstorder_Mean'} 101.50911764402797
{'original_firstorder_Median'} 110.59087554644861
{'original_firstorder_Minimum'} -57.541002674412546
{'original_firstorder_Range'} 272.41659968481133
{'original_firstorder_RobustMeanAbsoluteDeviation'} 33.77413024914361
{'original_firstorder_RootMeanSquared'} 119.4592542099465
{'original_firstorder_Skewness'} -0.1335931626706967
{'original_firstorder_TotalEnergy'} 22521577.14419369
{'original_firstorder_Uniformity'} 0.19301615356912594
{'original_firstorder_Variance'} 3591.345662684951
{'original_glcm_Autocorrelation'} 58.73946185473446
{'original_glcm_ClusterProminence'} 1270.5030841277003
{'original_glcm_ClusterShade'} -45.81863039087466
{'original_glcm_ClusterTendency'} 16.708608761083564
{'original_glcm_Contrast'} 3.3203511020062444
{'original_glcm_Correlation'} 0.6371571527042293
{'original_glcm_DifferenceAverage'} 1.123176544259113
{'original_glcm_DifferenceEntropy'} 1.8676301695093551
{'original_glcm_DifferenceVariance'} 1.696981037798832
{'original_glcm_Id'} 0.634674530781884
{'original_glcm_Idm'} 0.603434082660269
{'original_glcm_Idmn'} 0.9791973465824846
{'original_glcm_Idn'} 0.9211477690308509
{'original_glcm_Imc1'} -0.22535483968731707
{'original_glcm_Imc2'} 0.7684790428883036
{'original_glcm_InverseVariance'} 0.42854862887181167
{'original_glcm_JointAverage'} 7.314305440359281
{'original_glcm_JointEnergy'} 0.07206334778316177
{'original_glcm_JointEntropy'} 4.717882059765407
{'original_glcm_MCC'} 0.7351320691492885
{'original_glcm_MaximumProbability'} 0.17613560642684004
{'original_glcm_SumAverage'} 14.628610880718561
{'original_glcm_SumEntropy'} 3.507651158510645
{'original_glcm_SumSquares'} 5.007239965772453
{'original_gldm_DependenceEntropy'} 6.304354468206146
{'original_gldm_DependenceNonUniformity'} 101.81495217650404
{'original_gldm_DependenceNonUniformityNormalized'} 0.06976929479803144
{'original_gldm_DependenceVariance'} 19.81920556881658
{'original_gldm_GrayLevelNonUniformity'} 301.61943310900307
{'original_gldm_GrayLevelVariance'} 5.816464951123102
{'original_gldm_HighGrayLevelEmphasis'} 59.56351526347722
{'original_gldm_LargeDependenceEmphasis'} 89.83779376581715
{'original_gldm_LargeDependenceHighGrayLevelEmphasis'} 5627.225024195414
{'original_gldm_LargeDependenceLowGrayLevelEmphasis'} 2.3977556411240855
{'original_gldm_LowGrayLevelEmphasis'} 0.0385813882895411
{'original_gldm_SmallDependenceEmphasis'} 0.0634813528016483
{'original_gldm_SmallDependenceHighGrayLevelEmphasis'} 2.9544881032080084
{'original_gldm_SmallDependenceLowGrayLevelEmphasis'} 0.0038554378202323002
{'original_glrlm_GrayLevelNonUniformity'} 185.69365521223529
{'original_glrlm_GrayLevelNonUniformityNormalized'} 0.16461892231503858
{'original_glrlm_GrayLevelVariance'} 6.099699532760077
{'original_glrlm_HighGrayLevelRunEmphasis'} 57.73256953782754
{'original_glrlm_LongRunEmphasis'} 3.1766012790802436
{'original_glrlm_LongRunHighGrayLevelEmphasis'} 191.4166615966332
{'original_glrlm_LongRunLowGrayLevelEmphasis'} 0.10356754445378784
{'original_glrlm_LowGrayLevelRunEmphasis'} 0.0417973580571581
{'original_glrlm_RunEntropy'} 4.010322903116125
{'original_glrlm_RunLengthNonUniformity'} 623.543024085379
{'original_glrlm_RunLengthNonUniformityNormalized'} 0.579336173381228
{'original_glrlm_RunPercentage'} 0.719509255119647
{'original_glrlm_RunVariance'} 0.9180823250454063
{'original_glrlm_ShortRunEmphasis'} 0.7777140770879422
{'original_glrlm_ShortRunHighGrayLevelEmphasis'} 44.031762409733055
{'original_glrlm_ShortRunLowGrayLevelEmphasis'} 0.034840193606436635
{'original_glszm_GrayLevelNonUniformity'} 9.815874143933703
{'original_glszm_GrayLevelNonUniformityNormalized'} 0.13354562449758964
{'original_glszm_GrayLevelVariance'} 6.8197237490412626
{'original_glszm_HighGrayLevelZoneEmphasis'} 41.93882439063225
{'original_glszm_LargeAreaEmphasis'} 7263.261488812644
{'original_glszm_LargeAreaHighGrayLevelEmphasis'} 332465.5530397028
{'original_glszm_LargeAreaLowGrayLevelEmphasis'} 198.62355956797487
{'original_glszm_LowGrayLevelZoneEmphasis'} 0.0786472935109928
{'original_glszm_SizeZoneNonUniformity'} 14.69195399620583
{'original_glszm_SizeZoneNonUniformityNormalized'} 0.1938760937465532
{'original_glszm_SmallAreaEmphasis'} 0.42595378898966113
{'original_glszm_SmallAreaHighGrayLevelEmphasis'} 15.890959951584174
{'original_glszm_SmallAreaLowGrayLevelEmphasis'} 0.0322155758397338
{'original_glszm_ZoneEntropy'} 5.162135036273331
{'original_glszm_ZonePercentage'} 0.0621252874544282
{'original_glszm_ZoneVariance'} 6585.139003850461
{'original_ngtdm_Busyness'} 1.8334265555022455
{'original_ngtdm_Coarseness'} 0.0072237022552897
{'original_ngtdm_Complexity'} 42.53906478293958
{'original_ngtdm_Contrast'} 0.08230165336611349
{'original_ngtdm_Strength'} 0.4853245714466781

original_firstorder_Minimum
original_firstorder_10Percentile

In [67]:
df.loc[:19,["original_firstorder_Minimum","original_firstorder_10Percentile"]]

    original_firstorder_Minimum  original_firstorder_10Percentile
0                   -113.047603                        -68.168552
1                      1.260124                         91.098124
2                    -60.835530                         50.612435
3                   -103.529007                         98.212590
4                   -113.146797                         66.898865
5                    -96.432169                         -5.453843
6                   -546.721313                        -75.582722
7                   -133.621735                        -53.755154
8                    -77.354538                         11.303544
9                    -79.962639                         72.553980
10                  -802.000000                       -126.000000
11                   -94.000000                          1.000000
12                   -96.000000                         45.000000
13                  -101.000000                         31.000000
14                  -112.000000                         21.000000
15                   -86.000000                         15.000000
16                   -93.000000                         50.000000
17                   -95.000000                         -2.000000
18                  -111.000000                         25.000000
19                  -104.000000                          8.000000

In [68]:
df.loc[:19,["original_firstorder_Minimum","original_firstorder_10Percentile"]].to_dict()

{'original_firstorder_Minimum': {0: -113.04760270974634,
  1: 1.260124444961548,
  2: -60.83552975845284,
  3: -103.5290069580078,
  4: -113.14679718017578,
  5: -96.4321693239495,
  6: -546.7213134765625,
  7: -133.62173461914062,
  8: -77.35453796386719,
  9: -79.96263885498047,
  10: -802.0,
  11: -94.0,
  12: -96.0,
  13: -101.0,
  14: -112.0,
  15: -86.0,
  16: -93.0,
  17: -95.0,
  18: -111.0,
  19: -104.0},
 'original_firstorder_10Percentile': {0: -68.16855232195488,
  1: 91.09812393188476,
  2: 50.61243515113016,
  3: 98.21259002685548,
  4: 66.89886474609375,
  5: -5.453843023605804,
  6: -75.58272247314453,
  7: -53.75515441894531,
  8: 11.303544235229491,
  9: 72.55398025512697,
  10: -126.0,
  11: 1.0,
  12: 45.0,
  13: 31.0,
  14: 21.0,
  15: 15.0,
  16: 50.0,
  17: -2.0,
  18: 25.0,
  19: 8.0}}

In [71]:
df.columns.to_list()

['diagnostics_Versions_PyRadiomics',
 'diagnostics_Versions_Numpy',
 'diagnostics_Versions_SimpleITK',
 'diagnostics_Versions_PyWavelet',
 'diagnostics_Versions_Python',
 'diagnostics_Configuration_Settings',
 'diagnostics_Configuration_EnabledImageTypes',
 'diagnostics_Image-original_Hash',
 'diagnostics_Image-original_Dimensionality',
 'diagnostics_Image-original_Spacing',
 'diagnostics_Image-original_Size',
 'diagnostics_Image-original_Mean',
 'diagnostics_Image-original_Minimum',
 'diagnostics_Image-original_Maximum',
 'diagnostics_Mask-original_Hash',
 'diagnostics_Mask-original_Spacing',
 'diagnostics_Mask-original_Size',
 'diagnostics_Mask-original_BoundingBox',
 'diagnostics_Mask-original_VoxelNum',
 'diagnostics_Mask-original_VolumeNum',
 'diagnostics_Mask-original_CenterOfMassIndex',
 'diagnostics_Mask-original_CenterOfMass',
 'original_shape_Elongation',
 'original_shape_Flatness',
 'original_shape_LeastAxisLength',
 'original_shape_MajorAxisLength',
 'original_shape_Maximum2DDiameterColumn',
 'original_shape_Maximum2DDiameterRow',
 'original_shape_Maximum2DDiameterSlice',
 'original_shape_Maximum3DDiameter',
 'original_shape_MeshVolume',
 'original_shape_MinorAxisLength',
 'original_shape_Sphericity',
 'original_shape_SurfaceArea',
 'original_shape_SurfaceVolumeRatio',
 'original_shape_VoxelVolume',
 'original_firstorder_10Percentile',
 'original_firstorder_90Percentile',
 'original_firstorder_Energy',
 'original_firstorder_Entropy',
 'original_firstorder_InterquartileRange',
 'original_firstorder_Kurtosis',
 'original_firstorder_Maximum',
 'original_firstorder_MeanAbsoluteDeviation',
 'original_firstorder_Mean',
 'original_firstorder_Median',
 'original_firstorder_Minimum',
 'original_firstorder_Range',
 'original_firstorder_RobustMeanAbsoluteDeviation',
 'original_firstorder_RootMeanSquared',
 'original_firstorder_Skewness',
 'original_firstorder_TotalEnergy',
 'original_firstorder_Uniformity',
 'original_firstorder_Variance',
 'original_glcm_Autocorrelation',
 'original_glcm_ClusterProminence',
 'original_glcm_ClusterShade',
 'original_glcm_ClusterTendency',
 'original_glcm_Contrast',
 'original_glcm_Correlation',
 'original_glcm_DifferenceAverage',
 'original_glcm_DifferenceEntropy',
 'original_glcm_DifferenceVariance',
 'original_glcm_Id',
 'original_glcm_Idm',
 'original_glcm_Idmn',
 'original_glcm_Idn',
 'original_glcm_Imc1',
 'original_glcm_Imc2',
 'original_glcm_InverseVariance',
 'original_glcm_JointAverage',
 'original_glcm_JointEnergy',
 'original_glcm_JointEntropy',
 'original_glcm_MCC',
 'original_glcm_MaximumProbability',
 'original_glcm_SumAverage',
 'original_glcm_SumEntropy',
 'original_glcm_SumSquares',
 'original_gldm_DependenceEntropy',
 'original_gldm_DependenceNonUniformity',
 'original_gldm_DependenceNonUniformityNormalized',
 'original_gldm_DependenceVariance',
 'original_gldm_GrayLevelNonUniformity',
 'original_gldm_GrayLevelVariance',
 'original_gldm_HighGrayLevelEmphasis',
 'original_gldm_LargeDependenceEmphasis',
 'original_gldm_LargeDependenceHighGrayLevelEmphasis',
 'original_gldm_LargeDependenceLowGrayLevelEmphasis',
 'original_gldm_LowGrayLevelEmphasis',
 'original_gldm_SmallDependenceEmphasis',
 'original_gldm_SmallDependenceHighGrayLevelEmphasis',
 'original_gldm_SmallDependenceLowGrayLevelEmphasis',
 'original_glrlm_GrayLevelNonUniformity',
 'original_glrlm_GrayLevelNonUniformityNormalized',
 'original_glrlm_GrayLevelVariance',
 'original_glrlm_HighGrayLevelRunEmphasis',
 'original_glrlm_LongRunEmphasis',
 'original_glrlm_LongRunHighGrayLevelEmphasis',
 'original_glrlm_LongRunLowGrayLevelEmphasis',
 'original_glrlm_LowGrayLevelRunEmphasis',
 'original_glrlm_RunEntropy',
 'original_glrlm_RunLengthNonUniformity',
 'original_glrlm_RunLengthNonUniformityNormalized',
 'original_glrlm_RunPercentage',
 'original_glrlm_RunVariance',
 'original_glrlm_ShortRunEmphasis',
 'original_glrlm_ShortRunHighGrayLevelEmphasis',
 'original_glrlm_ShortRunLowGrayLevelEmphasis',
 'original_glszm_GrayLevelNonUniformity',
 'original_glszm_GrayLevelNonUniformityNormalized',
 'original_glszm_GrayLevelVariance',
 'original_glszm_HighGrayLevelZoneEmphasis',
 'original_glszm_LargeAreaEmphasis',
 'original_glszm_LargeAreaHighGrayLevelEmphasis',
 'original_glszm_LargeAreaLowGrayLevelEmphasis',
 'original_glszm_LowGrayLevelZoneEmphasis',
 'original_glszm_SizeZoneNonUniformity',
 'original_glszm_SizeZoneNonUniformityNormalized',
 'original_glszm_SmallAreaEmphasis',
 'original_glszm_SmallAreaHighGrayLevelEmphasis',
 'original_glszm_SmallAreaLowGrayLevelEmphasis',
 'original_glszm_ZoneEntropy',
 'original_glszm_ZonePercentage',
 'original_glszm_ZoneVariance',
 'original_ngtdm_Busyness',
 'original_ngtdm_Coarseness',
 'original_ngtdm_Complexity',
 'original_ngtdm_Contrast',
 'original_ngtdm_Strength',
 'case_id',
 'data_source']

In [3]:
df_ucsf = pd.read_csv("phase_reg_key.csv")

In [4]:
df_kits23 = pd.read_json("kits23.json")

In [78]:
df_ucsf

,pid,noncon,arterial,delay,portven,mask,ct_manufacturer,patient_age_years,patient_sex,pathology,tumor_type,pathology_grade,tumor_laterality,tumor_size_cm,tumor_biopsy_type
0,08FBroxzI6,2,0,1,1,2,GE MEDICAL SYSTEMS LightSpeed VCT,68,F,angiomyolipoma,angiomyolipoma,NaN,right,2.5,partial nephrectomy
1,0A87Rq5Hkl,2,1,0,0,2,GE MEDICAL SYSTEMS Discovery CT750 HD,90,F,oncocytoma,oncocytoma,NaN,left,2.3,image guided
2,0ByGP3oWJi,2,0,0,0,2,GE MEDICAL SYSTEMS LightSpeed16,48,M,clear cell,RCC,4.0,right,5.7,partial nephrectomy
3,0HW0RoqB2y,2,1,0,1,2,GE MEDICAL SYSTEMS LightSpeed VCT,39,M,cystic,RCC,1.0,left,3.2,partial nephrectomy
4,0MPL7wuVkw,2,0,2,2,2,GE MEDICAL SYSTEMS LightSpeed VCT,61,M,clear cell,RCC,3.0,right,3.6,partial nephrectomy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
826,zmwtNTDvF2,2,2,0,2,2,Philips Ingenuity CT,57,M,clear cell,RCC,2.0,left,3.9,radical nephrectomy
827,zrDL8HfWpB,2,0,2,2,2,GE MEDICAL SYSTEMS Discovery LS,52,M,clear cell,RCC,2.0,left,3.0,partial nephrectomy
828,zrvxpvxpGd,2,2,2,2,2,GE MEDICAL SYSTEMS LightSpeed Plus,74,F,NaN,NaN,NaN,NaN,NaN,NaN
829,zs9u4LLGez,2,1,1,0,2,TOSHIBA Aquilion,65,F,clear cell,RCC,2.0,left,4.9,partial nephrectomy
830,zsg5AUbKwd,2,0,1,1,2,SIEMENS Emotion 16,56,M,spindle cell lipoma,other,NaN,right,2.2,partial nephrectomy

In [5]:
pd.set_option("display.max_rows", 100)

In [6]:
df_ucsf.info()

<class 'pandas.DataFrame'>
RangeIndex: 831 entries, 0 to 830
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pid                831 non-null    str
 1   noncon             831 non-null    int64
 2   arterial           831 non-null    int64
 3   delay              831 non-null    int64
 4   portven            831 non-null    int64
 5   mask               831 non-null    int64
 6   ct_manufacturer    831 non-null    str
 7   patient_age_years  831 non-null    int64
 8   patient_sex        831 non-null    str
 9   pathology          821 non-null    str
 10  tumor_type         821 non-null    str
 11  pathology_grade    648 non-null    float64
 12  tumor_laterality   821 non-null    str
 13  tumor_size_cm      821 non-null    float64
 14  tumor_biopsy_type  819 non-null    str
dtypes: float64(2), int64(6), str(7)
memory usage: 161.0 KB

In [8]:
df_ucsf.columns

Index(['pid', 'noncon', 'arterial', 'delay', 'portven', 'mask',
       'ct_manufacturer', 'patient_age_years', 'patient_sex', 'pathology',
       'tumor_type', 'pathology_grade', 'tumor_laterality', 'tumor_size_cm',
       'tumor_biopsy_type'],
      dtype='str')

In [7]:
df_kits23.info()

<class 'pandas.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 40 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   case_id                         489 non-null    str
 1   gender                          489 non-null    str
 2   vital_status                    489 non-null    str
 3   vital_days_after_surgery        489 non-null    int64
 4   bmi                             488 non-null    float64
 5   comorbidities                   489 non-null    object
 6   age_at_nephrectomy              489 non-null    int64
 7   hospitalization                 489 non-null    int64
 8   er_visit                        487 non-null    float64
 9   readmission                     487 non-null    float64
 10  surgery_type                    489 non-null    str
 11  surgical_approach               488 non-null    str
 12  surgical_procedure              489 non-null    str
 13  estimated_blood_loss            480 non-null    float64
 14  clavien_surgical_complications  489 non-null    str
 15  intraoperative_complications    489 non-null    object
 16  ischemia_time                   259 non-null    float64
 17  operative_time                  484 non-null    float64
 18  smoking_history                 489 non-null    str
 19  age_when_quit_smoking           150 non-null    float64
 20  pack_years                      253 non-null    float64
 21  chewing_tobacco_use             488 non-null    str
 22  alcohol_use                     488 non-null    str
 23  radiographic_size               482 non-null    float64
 24  cytoreductive                   487 non-null    float64
 25  pathologic_size                 468 non-null    float64
 26  malignant                       482 non-null    float64
 27  pathology_t_stage               476 non-null    str
 28  pathology_n_stage               475 non-null    str
 29  pathology_m_stage               474 non-null    str
 30  tumor_histologic_subtype        483 non-null    str
 31  tumor_necrosis                  476 non-null    float64
 32  tumor_isup_grade                480 non-null    str
 33  positive_resection_margins      467 non-null    float64
 34  sarcomatoid_features            476 non-null    float64
 35  rhabdoid_features               476 non-null    float64
 36  last_preop_egfr                 489 non-null    object
 37  first_postop_egfr               489 non-null    object
 38  last_postop_egfr                489 non-null    object
 39  aua_risk_score                  483 non-null    str
dtypes: float64(16), int64(3), object(5), str(16)
memory usage: 231.5+ KB

In [9]:
df_kits23.columns

Index(['case_id', 'gender', 'vital_status', 'vital_days_after_surgery', 'bmi',
       'comorbidities', 'age_at_nephrectomy', 'hospitalization', 'er_visit',
       'readmission', 'surgery_type', 'surgical_approach',
       'surgical_procedure', 'estimated_blood_loss',
       'clavien_surgical_complications', 'intraoperative_complications',
       'ischemia_time', 'operative_time', 'smoking_history',
       'age_when_quit_smoking', 'pack_years', 'chewing_tobacco_use',
       'alcohol_use', 'radiographic_size', 'cytoreductive', 'pathologic_size',
       'malignant', 'pathology_t_stage', 'pathology_n_stage',
       'pathology_m_stage', 'tumor_histologic_subtype', 'tumor_necrosis',
       'tumor_isup_grade', 'positive_resection_margins',
       'sarcomatoid_features', 'rhabdoid_features', 'last_preop_egfr',
       'first_postop_egfr', 'last_postop_egfr', 'aua_risk_score'],
      dtype='str')

In [90]:
df_ucsf["pathology"].value_counts()

pathology
clear cell                                                                           476
oncocytoma                                                                           102
papillary                                                                             91
chromophobe                                                                           39
angiomyolipoma                                                                        29
renal cell carcinoma, NOS                                                             13
clear cell, papillary                                                                  7
simple cyst                                                                            6
cystic                                                                                 5
multilocular cystic                                                                    5
cystic nephroma                                                                        4
metastatic squamous cell carcinoma of the lung                                         2
acquired cystic disease-associated                                                     2
TFE3 translocation-associated                                                          2
arteriovenous malformation; prior hemorrhage with thrombosis                           1
papillary RCC (large one) and oncocytoma (small one)                                   1
collecting duct carcinoma                                                              1
anastomosing hemangioma                                                                1
chromophobe, oncocytic variant                                                         1
clear cell papillary type                                                              1
focal scar                                                                             1
inconclusive, possibly papillary tumor                                                 1
Multilocular cyst                                                                      1
TCEB-1 associated                                                                      1
mucinous tubular and spindle cell                                                      1
angiosarcoma                                                                           1
clear cell papillary tumor                                                             1
metastatic thyroid carcinoma                                                           1
TCEB1-mutated                                                                          1
paraganglioma                                                                          1
MiT family translocation                                                               1
leiomyoma                                                                              1
favoring papillary adenoma over papillary RCC; If papillary RCC, would be grade 2      1
infarct                                                                                1
papillary adenoma vs papillary RCC                                                     1
solitary fibrous tumor                                                                 1
tubular and spindle cell carcinoma                                                     1
medullary dysplasia vs prominent medullary pyramid                                     1
TFE3 translocation associated                                                          1
chronic inflammation                                                                   1
translocation                                                                          1
low grade RCC with oncocytic feature, possibly chromophobe RCC                         1
glomus tumor                                                                           1
focal fibrosis                                                                         1
cystic angiomyolipoma                                                                  1
perivascular epithelioid cell neoplasm, sclerosing-type                                1
tubular and spindle cell                                                               1
xanthogranulomatous pyelonephritis                                                     1
carcinoid                                                                              1
mucinous tubular                                                                       1
mucinous tubular and spindle cell carcinoma                                            1
spindle cell lipoma                                                                    1
Name: count, dtype: int64

In [91]:
df_ucsf["tumor_type"].value_counts()

tumor_type
RCC               647
oncocytoma        102
other              42
angiomyolipoma     30
Name: count, dtype: int64

In [99]:
df_ucsf[(df_ucsf["pathology"]!="angiomyolipoma") & (df_ucsf["tumor_type"]=="angiomyolipoma")]

,pid,noncon,arterial,delay,portven,mask,ct_manufacturer,patient_age_years,patient_sex,pathology,tumor_type,pathology_grade,tumor_laterality,tumor_size_cm,tumor_biopsy_type
534,dkp1S2CrhL,2,0,1,1,2,GE MEDICAL SYSTEMS LightSpeed16,29,F,cystic angiomyolipoma,angiomyolipoma,NaN,left,2.0,partial nephrectomy

In [98]:
df[ucsf[df_ucsf["tumor_type"]=="angiomyolipoma"].shape

/tmp/ipykernel_17702/586731379.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df_ucsf["tumor_type"]=="angiomyolipoma"].shape

(11, 131)